# Support Vector Machine (SVM)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('image_bins_stats_rskew.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X = dataset.iloc[:, 1:].values

In [4]:
print(X)

[[23.97606006  2.12693517  0.         ...  0.          5.61868087
   1.        ]
 [ 1.03465307  0.          0.         ...  0.          7.81662151
   1.        ]
 [21.61161972  0.          0.         ...  0.          6.49532838
   1.        ]
 ...
 [ 1.07391334  0.          0.         ...  0.          6.95591592
   0.        ]
 [ 1.10274681  0.          0.         ...  9.02107402  7.86127157
   0.        ]
 [ 1.1404188   0.          0.         ...  0.          8.09867216
   0.        ]]


In [5]:
print(y)

[1 1 1 ... 0 0 0]


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
print(X_train)

[[ 1.14062529  0.          0.         ...  0.          7.10246733
   1.        ]
 [ 1.36587954  0.          0.         ...  0.          8.51074261
   0.        ]
 [ 2.64697257  0.          0.         ...  0.          8.55644718
   1.        ]
 ...
 [22.59937459  2.67522539  0.         ...  0.         11.29961141
   1.        ]
 [ 1.22018154  0.          0.         ...  0.          4.92098789
   1.        ]
 [25.4918447   2.05463755  0.         ...  0.         12.42547376
   1.        ]]


In [8]:
print(y_train)

[1 0 1 ... 1 1 1]


In [9]:
print(X_test)

[[ 2.33401818  0.          0.         ...  0.          7.73755928
   1.        ]
 [ 1.03428436  0.90584722  0.         ...  0.          7.65068974
   1.        ]
 [ 1.25848989  0.          0.         ...  0.          4.24073814
   1.        ]
 ...
 [ 1.01179578  0.          0.         ...  0.          6.41853574
   1.        ]
 [ 1.23050011  0.39685026  0.         ...  0.         11.36014584
   1.        ]
 [ 2.51322808  0.          0.         ...  0.          6.321061
   1.        ]]


In [10]:
print(y_test)

[1 1 1 ... 1 1 1]


## Training the SVM model on the Training set

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2959    0]
 [   0 3041]]


1.0

In [13]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2959
           1       1.00      1.00      1.00      3041

    accuracy                           1.00      6000
   macro avg       1.00      1.00      1.00      6000
weighted avg       1.00      1.00      1.00      6000



In [14]:
from sklearn import svm, metrics
from sklearn.metrics import confusion_matrix
import seaborn as sns
print(confusion_matrix(y_test, y_pred))

print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
print('Sensitivity: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))

[[2959    0]
 [   0 3041]]
Accuracy: 1.000
F1 Score: 1.000
Sensitivity: 1.000
Precision: 1.000
Recall: 1.000
