# Decision Tree Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('image_bins_stats_gmean.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X = dataset.iloc[:, 1:].values

In [4]:
print(X)

[[  0.86099158  80.66666667   0.         ...   0.         159.2297289
    1.        ]
 [  0.27160494  89.5          0.         ...   0.         156.332014
    1.        ]
 [  0.85241875 105.           0.         ...   0.         159.6628451
    1.        ]
 ...
 [  0.26926648   0.           0.         ...   0.         150.9591809
    0.        ]
 [  0.29627983   0.           0.         ... 112.2857143  148.9128704
    0.        ]
 [  0.32016791   0.           0.         ...   0.         147.6666913
    0.        ]]


In [5]:
print(y)

[1 1 1 ... 0 0 0]


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
print(X_train)

[[  0.19178853   0.           0.         ...   0.         150.9391304
    1.        ]
 [  0.20848708   0.           0.         ...   0.         161.895409
    0.        ]
 [  0.25231308   0.           0.         ...   0.         144.0890647
    1.        ]
 ...
 [  0.64759825  40.           0.         ...   0.         116.6295962
    1.        ]
 [  0.20918919   0.           0.         ...   0.         144.4415151
    1.        ]
 [  1.60702703  67.58585859   0.         ...   0.         127.5543038
    1.        ]]


In [8]:
print(y_train)

[1 0 1 ... 1 1 1]


In [9]:
print(X_test)

[[  0.23708207   0.           0.         ...   0.         141.9584266
    1.        ]
 [  0.25805303  67.44444444   0.         ...   0.         146.0937447
    1.        ]
 [  0.19385965   0.           0.         ...   0.         173.9420438
    1.        ]
 ...
 [  0.22973245   0.           0.         ...   0.         134.2090304
    1.        ]
 [  0.30770702  55.5          0.         ...   0.         110.4028085
    1.        ]
 [  0.22911694   0.           0.         ...   0.         145.6202762
    1.        ]]


In [10]:
print(y_test)

[1 1 1 ... 1 1 1]


## Training the Decision Tree Classification model on the Training set

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2959    0]
 [   0 3041]]


1.0

In [13]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2959
           1       1.00      1.00      1.00      3041

    accuracy                           1.00      6000
   macro avg       1.00      1.00      1.00      6000
weighted avg       1.00      1.00      1.00      6000



In [14]:
from sklearn import svm, metrics
from sklearn.metrics import confusion_matrix
import seaborn as sns
print(confusion_matrix(y_test, y_pred))

print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
print('Sensitivity: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))

[[2959    0]
 [   0 3041]]
Accuracy: 1.000
F1 Score: 1.000
Sensitivity: 1.000
Precision: 1.000
Recall: 1.000
