In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import roc_auc_score, mean_squared_error

In [2]:
data = pd.read_csv('image_bins_stats_lungs4.csv')
data.shape

(3837, 106)

In [3]:
data.head()

filename  Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  \
0  transformed_image_covid_1.png   4722  15567      4   7683  12061      1   
1  transformed_image_covid_2.png   6556  13701     25   9956   9437      0   
2  transformed_image_covid_3.png  10512  12249      1  11502   7743      2   
3  transformed_image_covid_4.png   7987  11854      2  10419  11895      9   
4  transformed_image_covid_5.png   7761  14159      4  10898  10560      9   

   Bins6  Bins7  rmean_bins0  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0   8864  16634    77.433079  ...  29.26670025     39.092067     21.915792   
1  12114  13747    79.728951  ...  33.53821958     28.281468     23.127681   
2   9619  13908    68.987348  ...  25.22521593     26.681675     24.442798   
3  11931  11439    94.638788  ...  34.51618537     24.056261     28.558353   
4   9153  12992    68.762015  ...  32.13721328     27.884767     23.329477   

   bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5 bkurto_bins6  \
0     15.564234     10.232452     12.530200      0.000000    40.674295   
1     11.979449     17.519198     24.313131      0.000000    38.506228   
2      0.000000     12.323460     38.083555      4.204482    55.658016   
3      0.840896     13.800903     27.757483     33.449086    44.809595   
4     13.445587     16.742312     28.738945     26.135224    49.330295   

  bkurto_bins7 class  
0    31.538221     0  
1    36.562100     0  
2    27.952446     0  
3    37.884099     0  
4    35.162254     0  

[5 rows x 106 columns]

In [4]:
data = data.drop(['filename'], axis=1)
data.head()

Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7  rmean_bins0  \
0   4722  15567      4   7683  12061      1   8864  16634    77.433079   
1   6556  13701     25   9956   9437      0  12114  13747    79.728951   
2  10512  12249      1  11502   7743      2   9619  13908    68.987348   
3   7987  11854      2  10419  11895      9  11931  11439    94.638788   
4   7761  14159      4  10898  10560      9   9153  12992    68.762015   

   rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  bkurto_bins2  \
0     0.202929  ...  29.26670025     39.092067     21.915792     15.564234   
1     5.447851  ...  33.53821958     28.281468     23.127681     11.979449   
2    36.388358  ...  25.22521593     26.681675     24.442798      0.000000   
3    15.529948  ...  34.51618537     24.056261     28.558353      0.840896   
4     4.809379  ...  32.13721328     27.884767     23.329477     13.445587   

   bkurto_bins3  bkurto_bins4 bkurto_bins5 bkurto_bins6 bkurto_bins7 class  
0     10.232452     12.530200     0.000000    40.674295    31.538221     0  
1     17.519198     24.313131     0.000000    38.506228    36.562100     0  
2     12.323460     38.083555     4.204482    55.658016    27.952446     0  
3     13.800903     27.757483    33.449086    44.809595    37.884099     0  
4     16.742312     28.738945    26.135224    49.330295    35.162254     0  

[5 rows x 105 columns]

In [5]:
name = ['rstd_bins0','rstd_bins1','rstd_bins2','rstd_bins3','rstd_bins4','rstd_bins5','rstd_bins6','rstd_bins7','rskew_bins0','rskew_bins1','rskew_bins2','rskew_bins3','rskew_bins4','rskew_bins5','rskew_bins6','rskew_bins7','gstd_bins0','gstd_bins1','gstd_bins2','gstd_bins3','gstd_bins4','gstd_bins5','gstd_bins6','gstd_bins7','bstd_bins0','bstd_bins1','bstd_bins2','bstd_bins3','bstd_bins4','bstd_bins5','bstd_bins6','bstd_bins7','gskew_bins0','gskew_bins1','gskew_bins2','gskew_bins3','gskew_bins4','gskew_bins5','gskew_bins6','gskew_bins7','bskew_bins0','bskew_bins1','bskew_bins2','bskew_bins3','bskew_bins4','bskew_bins5','bskew_bins6','bskew_bins7','class']
for i in name:
    data[i] = pd.to_numeric(data[i],errors='coerce')

In [6]:
import numpy as np
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(data)

Bins0    Bins1  Bins2    Bins3    Bins4  Bins5    Bins6    Bins7  \
0      4722.0  15567.0    4.0   7683.0  12061.0    1.0   8864.0  16634.0   
1      6556.0  13701.0   25.0   9956.0   9437.0    0.0  12114.0  13747.0   
2     10512.0  12249.0    1.0  11502.0   7743.0    2.0   9619.0  13908.0   
3      7987.0  11854.0    2.0  10419.0  11895.0    9.0  11931.0  11439.0   
4      7761.0  14159.0    4.0  10898.0  10560.0    9.0   9153.0  12992.0   
...       ...      ...    ...      ...      ...    ...      ...      ...   
3832   9870.0  10436.0   13.0   9558.0   9764.0    0.0  16080.0   9815.0   
3833   5946.0  14026.0    1.0  11041.0  12415.0    0.0   7886.0  14221.0   
3834   7330.0   8408.0    6.0  10811.0  18521.0    2.0   6699.0  13759.0   
3835   7630.0  16431.0    1.0   9530.0   3413.0    3.0  17843.0  10685.0   
3836   5415.0  17347.0    0.0   8790.0  12865.0    2.0   8924.0  12193.0   

      rmean_bins0  rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0       77.433079     0.202929  ...    29.266700     39.092067     21.915792   
1       79.728951     5.447851  ...    33.538220     28.281468     23.127681   
2       68.987348    36.388358  ...    25.225216     26.681675     24.442798   
3       94.638788    15.529948  ...    34.516185     24.056261     28.558353   
4       68.762015     4.809379  ...    32.137213     27.884767     23.329477   
...           ...          ...  ...          ...           ...           ...   
3832   104.708207    27.440974  ...    28.826381     16.609479     32.541509   
3833    74.044736     1.607016  ...    39.246127     30.936390     21.337923   
3834   112.515416     7.136774  ...    28.790502     42.515393     18.625921   
3835    73.122412    24.310145  ...    37.426827     20.622111     29.148814   
3836    60.702862     1.042082  ...    34.588816     33.378388     26.261638   

      bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5  bkurto_bins6  \
0        15.564234     10.232452     12.530200      0.000000     40.674295   
1        11.979449     17.519198     24.313131      0.000000     38.506228   
2         0.000000     12.323460     38.083555      4.204482     55.658016   
3         0.840896     13.800903     27.757483     33.449086     44.809595   
4        13.445587     16.742312     28.738945     26.135224     49.330295   
...            ...           ...           ...           ...           ...   
3832     10.841782     18.263777     29.591836      0.000000     43.584547   
3833      0.000000      9.706518     17.877323      0.000000     45.339391   
3834     11.891740     14.170267      3.991819      0.000000     36.311970   
3835      0.000000     20.197666     31.678731      4.769168     50.967873   
3836      0.000000     17.291031     20.163037      5.045378     45.099627   

      bkurto_bins7  class  
0        31.538221    0.0  
1        36.562100    0.0  
2        27.952446    0.0  
3        37.884099    0.0  
4        35.162254    0.0  
...            ...    ...  
3832     43.219779    2.0  
3833     32.611797    2.0  
3834     41.914116    2.0  
3835     38.781249    2.0  
3836     35.944590    2.0  

[3823 rows x 105 columns]

In [7]:
# separate train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    data.drop(labels=['class'], axis=1),
    data['class'],
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((2676, 104), (1147, 104))

In [14]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

encoder = OrdinalEncoder()
data_encoded = encoder.fit_transform(data[features])
final_encoded = pd.DataFrame(data_encoded, columns=features)
encoder = LabelEncoder()
target_encoded = encoder.fit_transform(data['class'])
final_encoded['class'] = target_encoded

X_train, X_test, y_train, y_test = train_test_split(final_encoded.drop('class', axis=1), final_encoded['class'], test_size=0.3, random_state=143)

# determine roc-auc for each feature

# here we store the roc-auc values
roc_values = []

# iterate over each feature in the dataset
for feature in X_train.columns:

    # train a decision tree classifier
    clf = DecisionTreeClassifier()
    clf.fit(X_train[feature].fillna(0).to_frame(), y_train)

    # obtain the predictions
    y_scored = clf.predict_proba(X_test[feature].to_frame())

    # calculate and store the roc-auc
    roc_values.append(roc_auc_score(y_test, y_scored[:, 1], average='macro', multi_class='ovo'))
    
# display the result
roc_values[0:10]

NameError: name 'features' is not defined

In [10]:
# now let's:

# 1) capture the roc-auc values in a pandas series
# 2) add the variable names in the index
# 3) sort the features based on the roc-auc
# 4) and make a var plot

roc_values = pd.Series(roc_values)
roc_values.index = X_train.columns
roc_values.sort_values(ascending=False).plot.bar(figsize=(20, 5))
plt.ylabel('roc-auc')

<ipython-input-10-a6c15afc0be0>:8: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  roc_values = pd.Series(roc_values)


ValueError: Length mismatch: Expected axis has 0 elements, new values have 104 elements

In [10]:
# a roc auc value of 0.5 indicates random decision
# let's check how many features show a roc-auc value
# higher than random

len(roc_values[roc_values > 0.57])

30

In [11]:
selected_features = roc_values[roc_values > 0.6].index

selected_features

Index(['Bins5', 'rmean_bins7', 'bmean_bins2', 'bmean_bins5', 'bstd_bins3',
       'bskew_bins5', 'bkurto_bins6'],
      dtype='object')

In [12]:
# select features in the dataframes

X_train = X_train[selected_features]
X_test = X_test[selected_features]

X_train.shape, X_test.shape

((1735, 7), (744, 7))

In [13]:
# create a function to build random forests and
# compare its performance in train and test sets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
import scikitplot as skplt
import matplotlib.pyplot as plt

def run_randomForests(X_train, X_test, y_train, y_test):
    
    rf = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
    rf.fit(X_train, y_train)
    
    print('Train set')
    pred = rf.predict_proba(X_train)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = rf.predict_proba(X_test)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    y_pred = rf.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [14]:
# original
run_randomForests(X_train,
                  X_test,
                  y_train, y_test)

Train set
Random Forests roc-auc: 0.8668566349471923
Test set
Random Forests roc-auc: 0.8468274663189918
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.65      0.72       354
           1       0.73      0.86      0.79       390

    accuracy                           0.76       744
   macro avg       0.77      0.76      0.76       744
weighted avg       0.77      0.76      0.76       744

Confusion Matrix:
[[230 124]
 [ 53 337]]
Metrics:
Accuracy: 0.762
F1 Score: 0.792
Precision: 0.731
Recall: 0.864
After Cross Validation:
Accuracy: 75.05 %
Standard Deviation: 1.95 %


In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

def run_logistic(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    logit = LogisticRegression(penalty='l1', random_state=44, max_iter=1000, solver='liblinear')
    logit.fit(X_train, y_train)
    
    print('Train set')
    pred = logit.predict_proba(scaler.transform(X_train))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = logit.predict_proba(scaler.transform(X_test))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = logit.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = logit, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [16]:
run_logistic(X_train, X_test, y_train, y_test)

Train set
Logistic Regression roc-auc: 0.7836533434149244
Test set
Logistic Regression roc-auc: 0.7863465160075329
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.58      0.66       354
           1       0.69      0.83      0.75       390

    accuracy                           0.72       744
   macro avg       0.72      0.71      0.71       744
weighted avg       0.72      0.72      0.71       744

Confusion Matrix:
[[207 147]
 [ 65 325]]
Metrics:
Accuracy: 0.715
F1 Score: 0.754
Precision: 0.689
Recall: 0.833
After Cross Validation:
Accuracy: 71.47 %
Standard Deviation: 3.28 %


In [17]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_kernel_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [18]:
run_kernel_SVM(X_train, X_test, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.7242872502728197
Test set
Kernel SVM roc-auc: 0.7138997537302623
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.42      0.54       354
           1       0.62      0.87      0.73       390

    accuracy                           0.66       744
   macro avg       0.69      0.65      0.63       744
weighted avg       0.69      0.66      0.64       744

Confusion Matrix:
[[149 205]
 [ 49 341]]
Metrics:
Accuracy: 0.659
F1 Score: 0.729
Precision: 0.625
Recall: 0.874
After Cross Validation:
Accuracy: 65.82 %
Standard Deviation: 2.08 %


In [19]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.neighbors import KNeighborsClassifier

def run_knn(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [20]:
run_knn(X_train, X_test, y_train, y_test)

Train set
KNN roc-auc: 0.4993638676844784
Test set
KNN roc-auc: 0.4985875706214689
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.67      0.71       354
           1       0.73      0.81      0.77       390

    accuracy                           0.74       744
   macro avg       0.75      0.74      0.74       744
weighted avg       0.75      0.74      0.74       744

Confusion Matrix:
[[237 117]
 [ 74 316]]
Metrics:
Accuracy: 0.743
F1 Score: 0.768
Precision: 0.730
Recall: 0.810
After Cross Validation:
Accuracy: 74.52 %
Standard Deviation: 3.91 %


In [21]:
from sklearn.tree import DecisionTreeClassifier


def run_decision_tree(X_train, X_test, y_train, y_test):

    # function to train and test the performance of logistic regression
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(X_train)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(X_test)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [22]:
run_decision_tree(X_train, X_test, y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.7147544545849631
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.68      0.70       354
           1       0.72      0.75      0.73       390

    accuracy                           0.72       744
   macro avg       0.72      0.71      0.72       744
weighted avg       0.72      0.72      0.72       744

Confusion Matrix:
[[241 113]
 [ 98 292]]
Metrics:
Accuracy: 0.716
F1 Score: 0.735
Precision: 0.721
Recall: 0.749
After Cross Validation:
Accuracy: 70.83 %
Standard Deviation: 4.20 %


In [23]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.naive_bayes import GaussianNB

def run_naive_bayes(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [24]:
run_naive_bayes(X_train, X_test, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.6091238400137281
Test set
Kernel SVM roc-auc: 0.5744748660002897
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.35      0.50       354
           1       0.62      0.95      0.75       390

    accuracy                           0.67       744
   macro avg       0.74      0.65      0.62       744
weighted avg       0.74      0.67      0.63       744

Confusion Matrix:
[[123 231]
 [ 18 372]]
Metrics:
Accuracy: 0.665
F1 Score: 0.749
Precision: 0.617
Recall: 0.954
After Cross Validation:
Accuracy: 66.74 %
Standard Deviation: 2.52 %


In [29]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_linear_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'linear', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [30]:
run_linear_SVM(X_train, X_test, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.7594914023864616
Test set
Kernel SVM roc-auc: 0.8047149894440535
Classification Report:
              precision    recall  f1-score   support

         1.0       0.70      0.86      0.77       406
         2.0       0.82      0.62      0.71       399

    accuracy                           0.74       805
   macro avg       0.76      0.74      0.74       805
weighted avg       0.76      0.74      0.74       805

Confusion Matrix:
[[350  56]
 [151 248]]
Metrics:
Accuracy: 0.743
F1 Score: 0.772
Precision: 0.699
Recall: 0.862
After Cross Validation:
Accuracy: 70.82 %
Standard Deviation: 3.13 %
