# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv(r'C:\Users\Admin\Desktop\Statistical Moments using Bins\Machine Learning\rplane\mean\image_bins_stats_rmean.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
X = dataset.iloc[:, 1:].values

In [5]:
print(X)

[[  1.48568756 116.4166667    0.         ...   0.         159.7700147
    1.        ]
 [  0.1911294   91.           0.         ...   0.         149.8398539
    1.        ]
 [  1.218065   115.           0.         ...   0.         154.1894575
    1.        ]
 ...
 [  0.21742495   0.           0.         ...   0.         145.9154176
    0.        ]
 [  0.2261746    0.           0.         ... 114.4285714  144.3177797
    0.        ]
 [  0.22343064   0.           0.         ...   0.         141.1554408
    0.        ]]


In [6]:
print(y)

[1 1 1 ... 0 0 0]


## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
print(X_train)

[[  0.2727784    0.           0.         ...   0.         160.9055766
    1.        ]
 [  0.33733087   0.           0.         ...   0.         177.4334139
    0.        ]
 [  0.89122281   0.           0.         ...   0.         175.5484468
    1.        ]
 ...
 [  1.4010917  110.8965517    0.         ...   0.         149.9181351
    1.        ]
 [  0.27243243   0.           0.         ...   0.         158.9433983
    1.        ]
 [  2.46162162 101.8181818    0.         ...   0.         140.4350232
    1.        ]]


In [9]:
print(y_train)

[1 0 1 ... 1 1 1]


In [10]:
print(X_test)

[[6.87943262e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.71546210e+02 1.00000000e+00]
 [1.97722015e-01 1.01444444e+02 0.00000000e+00 ... 0.00000000e+00
  1.50751387e+02 1.00000000e+00]
 [3.01754386e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.84260842e+02 1.00000000e+00]
 ...
 [1.82860591e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.39794598e+02 1.00000000e+00]
 [2.62574106e-01 1.04500000e+02 0.00000000e+00 ... 0.00000000e+00
  1.46185912e+02 1.00000000e+00]
 [7.41713073e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.73090543e+02 1.00000000e+00]]


In [11]:
print(y_test)

[1 1 1 ... 1 1 1]


## Training the K-NN model on the Training set

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2852  107]
 [  15 3026]]


0.9796666666666667

In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      2959
           1       0.97      1.00      0.98      3041

    accuracy                           0.98      6000
   macro avg       0.98      0.98      0.98      6000
weighted avg       0.98      0.98      0.98      6000



In [15]:
from sklearn import svm, metrics
from sklearn.metrics import confusion_matrix
import seaborn as sns
print(confusion_matrix(y_test, y_pred))

print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
print('Sensitivity: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))

[[2852  107]
 [  15 3026]]
Accuracy: 0.980
F1 Score: 0.980
Sensitivity: 0.995
Precision: 0.966
Recall: 0.995
