In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import roc_auc_score, mean_squared_error, r2_score

In [4]:
data = data.drop(['filename'], axis=1)
data.head()

Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7  rmean_bins0  \
0   4722  15567      4   7683  12061      1   8864  16634    77.433079   
1   6556  13701     25   9956   9437      0  12114  13747    79.728951   
2  10512  12249      1  11502   7743      2   9619  13908    68.987348   
3   7987  11854      2  10419  11895      9  11931  11439    94.638788   
4   7761  14159      4  10898  10560      9   9153  12992    68.762015   

   rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  bkurto_bins2  \
0     0.202929  ...  29.26670025     39.092067     21.915792     15.564234   
1     5.447851  ...  33.53821958     28.281468     23.127681     11.979449   
2    36.388358  ...  25.22521593     26.681675     24.442798      0.000000   
3    15.529948  ...  34.51618537     24.056261     28.558353      0.840896   
4     4.809379  ...  32.13721328     27.884767     23.329477     13.445587   

   bkurto_bins3  bkurto_bins4 bkurto_bins5 bkurto_bins6 bkurto_bins7 class  
0     10.232452     12.530200     0.000000    40.674295    31.538221     0  
1     17.519198     24.313131     0.000000    38.506228    36.562100     0  
2     12.323460     38.083555     4.204482    55.658016    27.952446     0  
3     13.800903     27.757483    33.449086    44.809595    37.884099     0  
4     16.742312     28.738945    26.135224    49.330295    35.162254     0  

[5 rows x 105 columns]

In [5]:
name = ['rstd_bins0','rstd_bins1','rstd_bins2','rstd_bins3','rstd_bins4','rstd_bins5','rstd_bins6','rstd_bins7','gstd_bins0','gstd_bins1','gstd_bins2','gstd_bins3','gstd_bins4','gstd_bins5','gstd_bins6','gstd_bins7','bstd_bins0','bstd_bins1','bstd_bins2','bstd_bins3','bstd_bins4','bstd_bins5','bstd_bins6','bstd_bins7','gskew_bins0','gskew_bins1','gskew_bins2','gskew_bins3','gskew_bins4','gskew_bins5','gskew_bins6','gskew_bins7','bskew_bins0','bskew_bins1','bskew_bins2','bskew_bins3','bskew_bins4','bskew_bins5','bskew_bins6','bskew_bins7','class']
for i in name:
    data[i] = pd.to_numeric(data[i],errors='coerce')

In [6]:
import numpy as np
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(data)

Bins0    Bins1  Bins2    Bins3    Bins4  Bins5    Bins6    Bins7  \
0      4722.0  15567.0    4.0   7683.0  12061.0    1.0   8864.0  16634.0   
1      6556.0  13701.0   25.0   9956.0   9437.0    0.0  12114.0  13747.0   
2     10512.0  12249.0    1.0  11502.0   7743.0    2.0   9619.0  13908.0   
3      7987.0  11854.0    2.0  10419.0  11895.0    9.0  11931.0  11439.0   
4      7761.0  14159.0    4.0  10898.0  10560.0    9.0   9153.0  12992.0   
...       ...      ...    ...      ...      ...    ...      ...      ...   
2479   4950.0  16941.0    0.0   9161.0  12953.0    0.0   8179.0  13352.0   
2480   6149.0  11217.0    1.0  10795.0  14813.0    0.0   7335.0  15226.0   
2481   8157.0   8955.0    3.0   8384.0  14395.0    0.0   8516.0  17126.0   
2482   6614.0  11508.0    3.0  10639.0  14738.0    0.0   7195.0  14839.0   
2483   6026.0  14923.0    2.0  11764.0   9530.0    0.0   6751.0  16540.0   

      rmean_bins0  rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0       77.433079     0.202929  ...    29.266700     39.092067     21.915792   
1       79.728951     5.447851  ...    33.538220     28.281468     23.127681   
2       68.987348    36.388358  ...    25.225216     26.681675     24.442798   
3       94.638788    15.529948  ...    34.516185     24.056261     28.558353   
4       68.762015     4.809379  ...    32.137213     27.884767     23.329477   
...           ...          ...  ...          ...           ...           ...   
2479    59.237576     0.162269  ...    25.786782     40.580961     22.391613   
2480    89.067328     2.286262  ...    30.321740     38.459722     19.856163   
2481   110.959421    12.390955  ...    30.361398     40.138990     24.611149   
2482    90.745086     4.628172  ...    35.209322     29.755901     22.888434   
2483    50.459177     3.036186  ...    30.498729     34.411057     11.863055   

      bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5  bkurto_bins6  \
0        15.564234     10.232452     12.530200      0.000000     40.674295   
1        11.979449     17.519198     24.313131      0.000000     38.506228   
2         0.000000     12.323460     38.083555      4.204482     55.658016   
3         0.840896     13.800903     27.757483     33.449086     44.809595   
4        13.445587     16.742312     28.738945     26.135224     49.330295   
...            ...           ...           ...           ...           ...   
2479      0.000000      6.716628     15.733760      0.000000     45.642531   
2480      0.000000      7.773049     11.227728      0.000000     40.091211   
2481      8.738112     13.053664      9.750293      0.000000     32.766410   
2482     14.582557     13.300365     13.399057      0.000000     41.964578   
2483      0.840896      9.137053     17.018301      0.000000     42.159898   

      bkurto_bins7  class  
0        31.538221    0.0  
1        36.562100    0.0  
2        27.952446    0.0  
3        37.884099    0.0  
4        35.162254    0.0  
...            ...    ...  
2479     33.442984    1.0  
2480     34.380787    1.0  
2481     38.228325    1.0  
2482     34.453684    1.0  
2483     29.685276    1.0  

[2476 rows x 105 columns]

In [7]:
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    data.drop(labels=['class'], axis=1),
    data['class'],
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((1733, 104), (743, 104))

In [8]:
# for this method, it is necessary to reset the indeces of the returned 
# datasets

X_train.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)

In [9]:
# The first step to determine feature importance by feature shuffling
# is to build the machine learning model for which we want to 
# select features

# In this case, I will build Random Forests, but remember that 
# you can use this procedure with any other machine learning algorithm

# I build few and shallow trees to avoid overfitting
rf = RandomForestClassifier(
    n_estimators=50, max_depth=2, random_state=2909, n_jobs=4)

rf.fit(X_train, y_train)

# print roc-auc in train and testing sets
print('train auc score: ',
      roc_auc_score(y_train, (rf.predict_proba(X_train.fillna(0)))[:, 1]))
print('test auc score: ',
      roc_auc_score(y_test, (rf.predict_proba(X_test.fillna(0)))[:, 1]))

train auc score:  0.9642945353504166
test auc score:  0.954351145038168


In [10]:
# in this cell, I will shuffle one by one, each feature of the dataset

# then I use the dataset with the shuffled variable to make predictions
# with the random forests I trained in the previous cell

# overall train roc-auc: using all the features
train_roc = roc_auc_score(y_train, (rf.predict_proba(X_train))[:, 1])

# list to capture the performance shift
performance_shift = []

# selection  logic
for feature in X_train.columns:

    X_train_c = X_train.copy()

    # shuffle individual feature
    X_train_c[feature] = X_train_c[feature].sample(
        frac=1, random_state=10).reset_index(drop=True)

    # make prediction with shuffled feature and calculate roc-auc
    shuff_roc = roc_auc_score(y_train, rf.predict_proba(X_train_c)[:, 1])
    
    drift = train_roc - shuff_roc

    # save the drop in roc-auc
    performance_shift.append(drift)

In [11]:
# le't have a look at our list of performances
performance_shift

[0.0018973918412820145,
 0.0,
 0.00036780004563929936,
 0.0,
 0.0013020658550009223,
 0.0,
 0.0,
 0.0,
 0.0,
 0.00011074271447164552,
 0.0,
 0.00017718834315461063,
 0.0,
 0.0010510490355315483,
 0.0,
 1.140985543024442e-05,
 0.00015839564009278995,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0002785347060954013,
 0.002258480207256386,
 8.054015597891429e-06,
 0.0,
 0.0,
 2.953139052552789e-05,
 2.6175550693174898e-05,
 0.0,
 -7.986898801304321e-05,
 0.006417036927661379,
 0.00012416607380150158,
 0.0007550639623070676,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.00020739090164734186,
 0.0007537216263739932,
 6.040511698446327e-05,
 0.007915083828878844,
 -0.0002006792219821918,
 0.0,
 1.0738687463707208e-05,
 0.003814247553592609,
 0.0,
 0.0,
 0.00036645770970622493,
 0.00509148019383332,
 0.007004980066311339,
 5.6378109185573066e-05,
 0.0,
 0.0,
 0.0002349087882731471,
 0.0003422956629124396,
 0.00010335986684018028,
 9.12788434431766e-05,
 0.0002127602453788624,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 6.778796461581749e-05

In [12]:
# Now I will transform the list into a pandas Series
# for easy manipulation

feature_importance = pd.Series(performance_shift)

# add variable names in the index
feature_importance.index = X_train.columns

feature_importance.head()

Bins0    0.001897
Bins1    0.000000
Bins2    0.000368
Bins3    0.000000
Bins4    0.001302
dtype: float64

In [13]:
# Now I will sort the dataframe according to the drop in performance
# caused by feature shuffling

feature_importance.sort_values(ascending=False)

gmean_bins0     0.007915
gstd_bins1      0.007005
rskew_bins6     0.006417
gstd_bins0      0.005091
bstd_bins3      0.004686
                  ...   
rskew_bins5    -0.000080
bmean_bins1    -0.000100
bskew_bins5    -0.000126
gmean_bins1    -0.000201
rkurto_bins5   -0.000207
Length: 104, dtype: float64

In [14]:
# visualise the top 10 features that caused the major drop
# in the roc-auc (aka model performance)

feature_importance.sort_values(ascending=False).head(10)

gmean_bins0     0.007915
gstd_bins1      0.007005
rskew_bins6     0.006417
gstd_bins0      0.005091
bstd_bins3      0.004686
gmean_bins4     0.003814
gkurto_bins7    0.002535
rstd_bins6      0.002258
bmean_bins5     0.001932
Bins0           0.001897
dtype: float64

In [15]:
# original number of features (rows in this case)
feature_importance.shape[0]

104

In [16]:
# number of features that cause a drop in performance
# when shuffled

feature_importance[feature_importance>0].shape[0]

43

In [17]:
# print the important features

feature_importance[feature_importance>0].index

Index(['Bins0', 'Bins2', 'Bins4', 'rmean_bins1', 'rmean_bins3', 'rmean_bins5',
       'rmean_bins7', 'rstd_bins0', 'rstd_bins5', 'rstd_bins6', 'rstd_bins7',
       'rskew_bins2', 'rskew_bins3', 'rskew_bins6', 'rskew_bins7',
       'rkurto_bins0', 'rkurto_bins6', 'rkurto_bins7', 'gmean_bins0',
       'gmean_bins3', 'gmean_bins4', 'gmean_bins7', 'gstd_bins0', 'gstd_bins1',
       'gstd_bins2', 'gstd_bins5', 'gstd_bins6', 'gstd_bins7', 'gskew_bins0',
       'gskew_bins1', 'gskew_bins7', 'gkurto_bins0', 'gkurto_bins3',
       'gkurto_bins6', 'gkurto_bins7', 'bmean_bins4', 'bmean_bins5',
       'bstd_bins3', 'bstd_bins4', 'bstd_bins5', 'bskew_bins3', 'bkurto_bins4',
       'bkurto_bins6'],
      dtype='object')

In [18]:
# create a function to build random forests and
# compare its performance in train and test sets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score, mean_squared_error
import scikitplot as skplt
import matplotlib.pyplot as plt

def run_randomForests(X_train, X_test, y_train, y_test):
    
    rf = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
    rf.fit(X_train, y_train)
    
    print('Train set')
    pred = rf.predict_proba(X_train)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = rf.predict_proba(X_test)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    y_pred = rf.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [20]:
selected_features = feature_importance[feature_importance > 0].index
run_randomForests(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
Random Forests roc-auc: 0.9847107937232372
Test set
Random Forests roc-auc: 0.969807342784442
Classification Report:
              precision    recall  f1-score   support

         0.0       0.93      0.89      0.91       350
         1.0       0.91      0.94      0.92       393

    accuracy                           0.92       743
   macro avg       0.92      0.92      0.92       743
weighted avg       0.92      0.92      0.92       743

Confusion Matrix:
[[313  37]
 [ 23 370]]
Metrics:
Accuracy: 0.919
F1 Score: 0.925
Precision: 0.909
Recall: 0.941
After Cross Validation:
Accuracy: 91.98 %
Standard Deviation: 1.97 %


In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

def run_logistic(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    logit = LogisticRegression(penalty='l1', random_state=44, max_iter=1000, solver='liblinear')
    logit.fit(X_train, y_train)
    
    print('Train set')
    pred = logit.predict_proba(scaler.transform(X_train))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = logit.predict_proba(scaler.transform(X_test))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = logit.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = logit, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [22]:
run_logistic(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
Logistic Regression roc-auc: 0.9783789951273206
Test set
Logistic Regression roc-auc: 0.9712831697564522
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.93      0.95       350
         1.0       0.94      0.96      0.95       393

    accuracy                           0.95       743
   macro avg       0.95      0.95      0.95       743
weighted avg       0.95      0.95      0.95       743

Confusion Matrix:
[[327  23]
 [ 14 379]]
Metrics:
Accuracy: 0.950
F1 Score: 0.953
Precision: 0.943
Recall: 0.964
After Cross Validation:
Accuracy: 94.12 %
Standard Deviation: 1.78 %


In [23]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_kernel_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [24]:
run_kernel_SVM(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
Kernel SVM roc-auc: 0.9054686765910037
Test set
Kernel SVM roc-auc: 0.8992875318066158
Classification Report:
              precision    recall  f1-score   support

         0.0       0.79      0.66      0.72       350
         1.0       0.74      0.85      0.79       393

    accuracy                           0.76       743
   macro avg       0.76      0.75      0.75       743
weighted avg       0.76      0.76      0.75       743

Confusion Matrix:
[[230 120]
 [ 60 333]]
Metrics:
Accuracy: 0.758
F1 Score: 0.787
Precision: 0.735
Recall: 0.847
After Cross Validation:
Accuracy: 75.07 %
Standard Deviation: 2.66 %


In [25]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.neighbors import KNeighborsClassifier

def run_knn(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [26]:
run_knn(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
KNN roc-auc: 0.5
Test set
KNN roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.82      0.74      0.78       350
         1.0       0.79      0.85      0.82       393

    accuracy                           0.80       743
   macro avg       0.80      0.80      0.80       743
weighted avg       0.80      0.80      0.80       743

Confusion Matrix:
[[260  90]
 [ 59 334]]
Metrics:
Accuracy: 0.799
F1 Score: 0.818
Precision: 0.788
Recall: 0.850
After Cross Validation:
Accuracy: 79.22 %
Standard Deviation: 3.11 %


In [27]:
from sklearn.tree import DecisionTreeClassifier


def run_decision_tree(X_train, X_test, y_train, y_test):

    # function to train and test the performance of logistic regression
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(X_train)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(X_test)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [28]:
run_decision_tree(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.8846673936750272
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.87      0.88       350
         1.0       0.89      0.90      0.89       393

    accuracy                           0.89       743
   macro avg       0.89      0.88      0.89       743
weighted avg       0.89      0.89      0.89       743

Confusion Matrix:
[[304  46]
 [ 39 354]]
Metrics:
Accuracy: 0.886
F1 Score: 0.893
Precision: 0.885
Recall: 0.901
After Cross Validation:
Accuracy: 89.27 %
Standard Deviation: 2.09 %


In [29]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.naive_bayes import GaussianNB

def run_naive_bayes(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [30]:
run_naive_bayes(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.88      0.88       350
         1.0       0.89      0.91      0.90       393

    accuracy                           0.89       743
   macro avg       0.89      0.89      0.89       743
weighted avg       0.89      0.89      0.89       743

Confusion Matrix:
[[307  43]
 [ 37 356]]
Metrics:
Accuracy: 0.892
F1 Score: 0.899
Precision: 0.892
Recall: 0.906
After Cross Validation:
Accuracy: 88.35 %
Standard Deviation: 2.56 %


In [31]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_linear_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'linear', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
run_linear_SVM(X_train[selected_features], X_test[selected_features], y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5550632911392406
Test set
Kernel SVM roc-auc: 0.5471428571428572
Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      0.90      0.92       350
         1.0       0.91      0.96      0.94       393

    accuracy                           0.93       743
   macro avg       0.93      0.93      0.93       743
weighted avg       0.93      0.93      0.93       743

Confusion Matrix:
[[314  36]
 [ 15 378]]
Metrics:
Accuracy: 0.931
F1 Score: 0.937
Precision: 0.913
Recall: 0.962
After Cross Validation:
