In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('image_bins_stats_lungs1.csv')
data.shape

(2484, 106)

In [3]:
data.head()

filename  Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  \
0  transformed_image_covid_1.png   4722  15567      4   7683  12061      1   
1  transformed_image_covid_2.png   6556  13701     25   9956   9437      0   
2  transformed_image_covid_3.png  10512  12249      1  11502   7743      2   
3  transformed_image_covid_4.png   7987  11854      2  10419  11895      9   
4  transformed_image_covid_5.png   7761  14159      4  10898  10560      9   

   Bins6  Bins7  rmean_bins0  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0   8864  16634    77.433079  ...  29.26670025     39.092067     21.915792   
1  12114  13747    79.728951  ...  33.53821958     28.281468     23.127681   
2   9619  13908    68.987348  ...  25.22521593     26.681675     24.442798   
3  11931  11439    94.638788  ...  34.51618537     24.056261     28.558353   
4   9153  12992    68.762015  ...  32.13721328     27.884767     23.329477   

   bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5 bkurto_bins6  \
0     15.564234     10.232452     12.530200      0.000000    40.674295   
1     11.979449     17.519198     24.313131      0.000000    38.506228   
2      0.000000     12.323460     38.083555      4.204482    55.658016   
3      0.840896     13.800903     27.757483     33.449086    44.809595   
4     13.445587     16.742312     28.738945     26.135224    49.330295   

  bkurto_bins7 class  
0    31.538221     0  
1    36.562100     0  
2    27.952446     0  
3    37.884099     0  
4    35.162254     0  

[5 rows x 106 columns]

In [4]:
data = data.drop(['filename'], axis=1)
data.head()

Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7  rmean_bins0  \
0   4722  15567      4   7683  12061      1   8864  16634    77.433079   
1   6556  13701     25   9956   9437      0  12114  13747    79.728951   
2  10512  12249      1  11502   7743      2   9619  13908    68.987348   
3   7987  11854      2  10419  11895      9  11931  11439    94.638788   
4   7761  14159      4  10898  10560      9   9153  12992    68.762015   

   rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  bkurto_bins2  \
0     0.202929  ...  29.26670025     39.092067     21.915792     15.564234   
1     5.447851  ...  33.53821958     28.281468     23.127681     11.979449   
2    36.388358  ...  25.22521593     26.681675     24.442798      0.000000   
3    15.529948  ...  34.51618537     24.056261     28.558353      0.840896   
4     4.809379  ...  32.13721328     27.884767     23.329477     13.445587   

   bkurto_bins3  bkurto_bins4 bkurto_bins5 bkurto_bins6 bkurto_bins7 class  
0     10.232452     12.530200     0.000000    40.674295    31.538221     0  
1     17.519198     24.313131     0.000000    38.506228    36.562100     0  
2     12.323460     38.083555     4.204482    55.658016    27.952446     0  
3     13.800903     27.757483    33.449086    44.809595    37.884099     0  
4     16.742312     28.738945    26.135224    49.330295    35.162254     0  

[5 rows x 105 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Columns: 105 entries, Bins0 to class
dtypes: float64(56), int64(8), object(41)
memory usage: 2.0+ MB


In [6]:
name = ['rstd_bins0','rstd_bins1','rstd_bins2','rstd_bins3','rstd_bins4','rstd_bins5','rstd_bins6','rstd_bins7','gstd_bins0','gstd_bins1','gstd_bins2','gstd_bins3','gstd_bins4','gstd_bins5','gstd_bins6','gstd_bins7','bstd_bins0','bstd_bins1','bstd_bins2','bstd_bins3','bstd_bins4','bstd_bins5','bstd_bins6','bstd_bins7','gskew_bins0','gskew_bins1','gskew_bins2','gskew_bins3','gskew_bins4','gskew_bins5','gskew_bins6','gskew_bins7','bskew_bins0','bskew_bins1','bskew_bins2','bskew_bins3','bskew_bins4','bskew_bins5','bskew_bins6','bskew_bins7','class']
for i in name:
    data[i] = pd.to_numeric(data[i],errors='coerce')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Columns: 105 entries, Bins0 to class
dtypes: float64(97), int64(8)
memory usage: 2.0 MB


In [8]:
import numpy as np
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(data)

Bins0    Bins1  Bins2    Bins3    Bins4  Bins5    Bins6    Bins7  \
0      4722.0  15567.0    4.0   7683.0  12061.0    1.0   8864.0  16634.0   
1      6556.0  13701.0   25.0   9956.0   9437.0    0.0  12114.0  13747.0   
2     10512.0  12249.0    1.0  11502.0   7743.0    2.0   9619.0  13908.0   
3      7987.0  11854.0    2.0  10419.0  11895.0    9.0  11931.0  11439.0   
4      7761.0  14159.0    4.0  10898.0  10560.0    9.0   9153.0  12992.0   
...       ...      ...    ...      ...      ...    ...      ...      ...   
2479   4950.0  16941.0    0.0   9161.0  12953.0    0.0   8179.0  13352.0   
2480   6149.0  11217.0    1.0  10795.0  14813.0    0.0   7335.0  15226.0   
2481   8157.0   8955.0    3.0   8384.0  14395.0    0.0   8516.0  17126.0   
2482   6614.0  11508.0    3.0  10639.0  14738.0    0.0   7195.0  14839.0   
2483   6026.0  14923.0    2.0  11764.0   9530.0    0.0   6751.0  16540.0   

      rmean_bins0  rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0       77.433079     0.202929  ...    29.266700     39.092067     21.915792   
1       79.728951     5.447851  ...    33.538220     28.281468     23.127681   
2       68.987348    36.388358  ...    25.225216     26.681675     24.442798   
3       94.638788    15.529948  ...    34.516185     24.056261     28.558353   
4       68.762015     4.809379  ...    32.137213     27.884767     23.329477   
...           ...          ...  ...          ...           ...           ...   
2479    59.237576     0.162269  ...    25.786782     40.580961     22.391613   
2480    89.067328     2.286262  ...    30.321740     38.459722     19.856163   
2481   110.959421    12.390955  ...    30.361398     40.138990     24.611149   
2482    90.745086     4.628172  ...    35.209322     29.755901     22.888434   
2483    50.459177     3.036186  ...    30.498729     34.411057     11.863055   

      bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5  bkurto_bins6  \
0        15.564234     10.232452     12.530200      0.000000     40.674295   
1        11.979449     17.519198     24.313131      0.000000     38.506228   
2         0.000000     12.323460     38.083555      4.204482     55.658016   
3         0.840896     13.800903     27.757483     33.449086     44.809595   
4        13.445587     16.742312     28.738945     26.135224     49.330295   
...            ...           ...           ...           ...           ...   
2479      0.000000      6.716628     15.733760      0.000000     45.642531   
2480      0.000000      7.773049     11.227728      0.000000     40.091211   
2481      8.738112     13.053664      9.750293      0.000000     32.766410   
2482     14.582557     13.300365     13.399057      0.000000     41.964578   
2483      0.840896      9.137053     17.018301      0.000000     42.159898   

      bkurto_bins7  class  
0        31.538221    0.0  
1        36.562100    0.0  
2        27.952446    0.0  
3        37.884099    0.0  
4        35.162254    0.0  
...            ...    ...  
2479     33.442984    1.0  
2480     34.380787    1.0  
2481     38.228325    1.0  
2482     34.453684    1.0  
2483     29.685276    1.0  

[2476 rows x 105 columns]

In [9]:
# separate train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    data.drop(labels=['class'], axis=1),
    data['class'],
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((1733, 104), (743, 104))

In [10]:
# linear models benefit from feature scaling

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [42]:
# here I will do the model fitting and feature selection
# altogether in one line of code

# first I specify the Logistic Regression model, and I
# make sure I select the Lasso (l1) penalty.

# Then I use the selectFromModel class from sklearn, which
# will select the features which coefficients are non-zero

sel_ = SelectFromModel(
    LogisticRegression(C=0.1, penalty='l1', solver='liblinear', random_state=10))

sel_.fit(scaler.transform(X_train), y_train)

SelectFromModel(estimator=LogisticRegression(C=0.1, penalty='l1',
                                             random_state=10,
                                             solver='liblinear'))

In [43]:
# this command let's me visualise the index of the
# features that were selected

sel_.get_support()

array([ True,  True, False,  True, False, False, False,  True,  True,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False,  True,  True,  True, False, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False,  True,  True, False,  True, False,  True,
        True,  True, False, False, False, False, False, False,  True,
        True,  True, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False,  True,
        True, False,  True,  True,  True, False, False,  True, False,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False, False, False])

In [44]:
# Now I make a list with the selected features
selected_feat = X_train.columns[(sel_.get_support())]

print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(sel_.estimator_.coef_ == 0)))

total features: 104
selected features: 40
features with coefficients shrank to zero: 64


In [45]:
# the number of features which coefficient was shrank to zero:
np.sum(sel_.estimator_.coef_ == 0)

64

In [46]:
# we can identify the removed features like this:

removed_feats = X_train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

Index(['Bins2', 'Bins4', 'Bins5', 'Bins6', 'rmean_bins1', 'rmean_bins2',
       'rmean_bins3', 'rmean_bins6', 'rmean_bins7', 'rstd_bins0', 'rstd_bins1',
       'rstd_bins2', 'rstd_bins3', 'rstd_bins4', 'rskew_bins0', 'rskew_bins1',
       'rskew_bins3', 'rskew_bins4', 'rskew_bins7', 'rkurto_bins2',
       'rkurto_bins3', 'rkurto_bins4', 'rkurto_bins5', 'rkurto_bins6',
       'gmean_bins0', 'gmean_bins1', 'gmean_bins2', 'gmean_bins3',
       'gmean_bins4', 'gmean_bins6', 'gmean_bins7', 'gstd_bins2', 'gstd_bins4',
       'gskew_bins0', 'gskew_bins1', 'gskew_bins2', 'gskew_bins3',
       'gskew_bins4', 'gskew_bins5', 'gkurto_bins1', 'gkurto_bins2',
       'gkurto_bins3', 'gkurto_bins4', 'gkurto_bins5', 'gkurto_bins7',
       'bmean_bins0', 'bmean_bins1', 'bmean_bins2', 'bmean_bins3',
       'bmean_bins4', 'bmean_bins6', 'bmean_bins7', 'bstd_bins2', 'bstd_bins6',
       'bstd_bins7', 'bskew_bins1', 'bskew_bins2', 'bskew_bins4',
       'bskew_bins6', 'bskew_bins7', 'bkurto_bins3', 'bkurto_b

In [47]:
# we can then remove the features from the training and testing set
# like this:

X_train_selected = sel_.transform(X_train)
X_test_selected = sel_.transform(X_test)

X_train_selected.shape, X_test_selected.shape

((1733, 40), (743, 40))

In [48]:
selected_features = X_train.columns

In [18]:
# create a function to build random forests and
# compare its performance in train and test sets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score, mean_squared_error
import scikitplot as skplt
import matplotlib.pyplot as plt

def run_randomForests(X_train, X_test, y_train, y_test):
    
    rf = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
    rf.fit(X_train, y_train)
    
    print('Train set')
    pred = rf.predict_proba(X_train)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = rf.predict_proba(X_test)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    y_pred = rf.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [50]:
run_randomForests(X_train_selected, X_test_selected, y_train, y_test)

Train set
Random Forests roc-auc: 0.9841027155455925
Test set
Random Forests roc-auc: 0.970367139222101
Classification Report:
              precision    recall  f1-score   support

         0.0       0.94      0.89      0.91       350
         1.0       0.91      0.95      0.93       393

    accuracy                           0.92       743
   macro avg       0.92      0.92      0.92       743
weighted avg       0.92      0.92      0.92       743

Confusion Matrix:
[[312  38]
 [ 21 372]]
Metrics:
Accuracy: 0.921
F1 Score: 0.927
Precision: 0.907
Recall: 0.947
After Cross Validation:
Accuracy: 91.69 %
Standard Deviation: 1.64 %


In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

def run_logistic(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    logit = LogisticRegression(penalty='l1', random_state=44, max_iter=1000, solver='liblinear')
    logit.fit(X_train, y_train)
    
    print('Train set')
    pred = logit.predict_proba(scaler.transform(X_train))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = logit.predict_proba(scaler.transform(X_test))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = logit.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = logit, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [52]:
run_logistic(X_train_selected, X_test_selected, y_train, y_test)

Train set
Logistic Regression roc-auc: 0.9227874947984482
Test set
Logistic Regression roc-auc: 0.9067684478371502
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.92      0.94       350
         1.0       0.93      0.96      0.95       393

    accuracy                           0.94       743
   macro avg       0.95      0.94      0.94       743
weighted avg       0.95      0.94      0.94       743

Confusion Matrix:
[[323  27]
 [ 14 379]]
Metrics:
Accuracy: 0.945
F1 Score: 0.949
Precision: 0.933
Recall: 0.964
After Cross Validation:
Accuracy: 94.46 %
Standard Deviation: 2.19 %


In [20]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_kernel_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [54]:
run_kernel_SVM(X_train_selected, X_test_selected, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5144408499671128
Test set
Kernel SVM roc-auc: 0.5384223918575064
Classification Report:
              precision    recall  f1-score   support

         0.0       0.90      0.60      0.72       350
         1.0       0.73      0.94      0.82       393

    accuracy                           0.78       743
   macro avg       0.81      0.77      0.77       743
weighted avg       0.81      0.78      0.77       743

Confusion Matrix:
[[210 140]
 [ 23 370]]
Metrics:
Accuracy: 0.781
F1 Score: 0.819
Precision: 0.725
Recall: 0.941
After Cross Validation:
Accuracy: 76.75 %
Standard Deviation: 2.86 %


In [21]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.neighbors import KNeighborsClassifier

def run_knn(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [56]:
run_knn(X_train_selected, X_test_selected, y_train, y_test)

Train set
KNN roc-auc: 0.5
Test set
KNN roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.82      0.85       350
         1.0       0.85      0.91      0.88       393

    accuracy                           0.87       743
   macro avg       0.87      0.86      0.86       743
weighted avg       0.87      0.87      0.86       743

Confusion Matrix:
[[287  63]
 [ 37 356]]
Metrics:
Accuracy: 0.865
F1 Score: 0.877
Precision: 0.850
Recall: 0.906
After Cross Validation:
Accuracy: 84.71 %
Standard Deviation: 3.31 %


In [22]:
from sklearn.tree import DecisionTreeClassifier


def run_decision_tree(X_train, X_test, y_train, y_test):

    # function to train and test the performance of logistic regression
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(X_train)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(X_test)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [58]:
run_decision_tree(X_train_selected, X_test_selected, y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.8946673936750272
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.89      0.89       350
         1.0       0.90      0.90      0.90       393

    accuracy                           0.90       743
   macro avg       0.89      0.89      0.89       743
weighted avg       0.90      0.90      0.90       743

Confusion Matrix:
[[311  39]
 [ 39 354]]
Metrics:
Accuracy: 0.895
F1 Score: 0.901
Precision: 0.901
Recall: 0.901
After Cross Validation:
Accuracy: 89.04 %
Standard Deviation: 2.00 %


In [23]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_linear_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'linear', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
run_linear_SVM(X_train_selected, X_test_selected, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.95      0.93      0.94       350
         1.0       0.94      0.95      0.94       393

    accuracy                           0.94       743
   macro avg       0.94      0.94      0.94       743
weighted avg       0.94      0.94      0.94       743

Confusion Matrix:
[[324  26]
 [ 18 375]]
Metrics:
Accuracy: 0.941
F1 Score: 0.945
Precision: 0.935
Recall: 0.954
After Cross Validation:


In [24]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.naive_bayes import GaussianNB

def run_naive_bayes(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [61]:
run_naive_bayes(X_train_selected, X_test_selected, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.49936708860759493
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.90      0.88      0.89       350
         1.0       0.90      0.91      0.90       393

    accuracy                           0.90       743
   macro avg       0.90      0.90      0.90       743
weighted avg       0.90      0.90      0.90       743

Confusion Matrix:
[[308  42]
 [ 35 358]]
Metrics:
Accuracy: 0.896
F1 Score: 0.903
Precision: 0.895
Recall: 0.911
After Cross Validation:
Accuracy: 88.46 %
Standard Deviation: 2.11 %


In [11]:
# For comparison, I will fit a logistic regression with a
# Ridge regularisation, and evaluate the coefficients

l1_logit = LogisticRegression(C=0.5, penalty='l2', max_iter=300, random_state=10)
l1_logit.fit(scaler.transform(X_train), y_train)

# I count the number of coefficients with zero values
# and it is zero, as expected
np.sum(l1_logit.coef_ == 0)

0

In [12]:
# here I will do the model fitting and feature selection
# altogether in one line of code

# first I specify the Logistic Regression model, and I
# make sure I select the Lasso (l1) penalty.

# Then I use the selectFromModel class from sklearn, which
# will select the features which coefficients are non-zero

sel_ = SelectFromModel(
    LogisticRegression(C=0.5, penalty='l2', solver='liblinear', random_state=10))

sel_.fit(scaler.transform(X_train), y_train)

SelectFromModel(estimator=LogisticRegression(C=0.5, random_state=10,
                                             solver='liblinear'))

In [13]:
# this command let's me visualise the index of the
# features that were selected

sel_.get_support()

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False, False, False,  True,  True, False, False, False, False,
       False,  True,  True, False,  True,  True, False, False, False,
        True,  True, False,  True, False,  True,  True, False, False,
        True, False,  True,  True,  True, False, False,  True, False,
        True, False, False,  True, False, False,  True, False, False,
        True,  True, False, False, False, False, False, False,  True,
        True,  True, False, False, False, False, False,  True, False,
       False,  True, False,  True, False,  True, False, False,  True,
        True, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False])

In [14]:
# Now I make a list with the selected features
selected_feat = X_train.columns[(sel_.get_support())]

print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(sel_.estimator_.coef_ == 0)))

total features: 104
selected features: 41
features with coefficients shrank to zero: 0


In [15]:
# we can identify the removed features like this:

removed_feats = X_train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

Index([], dtype='object')

In [16]:
# we can then remove the features from the training and testing set
# like this:

X_train_ridge = sel_.transform(X_train)
X_test_ridge = sel_.transform(X_test)

X_train_ridge.shape, X_test_ridge.shape

((1733, 41), (743, 41))

In [25]:
run_randomForests(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Random Forests roc-auc: 0.9852007463387787
Test set
Random Forests roc-auc: 0.9729843693202471
Classification Report:
              precision    recall  f1-score   support

         0.0       0.93      0.90      0.91       350
         1.0       0.91      0.94      0.93       393

    accuracy                           0.92       743
   macro avg       0.92      0.92      0.92       743
weighted avg       0.92      0.92      0.92       743

Confusion Matrix:
[[315  35]
 [ 24 369]]
Metrics:
Accuracy: 0.921
F1 Score: 0.926
Precision: 0.913
Recall: 0.939
After Cross Validation:
Accuracy: 91.69 %
Standard Deviation: 1.78 %


In [26]:
run_logistic(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Logistic Regression roc-auc: 0.9265863054888117
Test set
Logistic Regression roc-auc: 0.9158197019265721
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.93      0.94       350
         1.0       0.94      0.96      0.95       393

    accuracy                           0.95       743
   macro avg       0.95      0.95      0.95       743
weighted avg       0.95      0.95      0.95       743

Confusion Matrix:
[[326  24]
 [ 15 378]]
Metrics:
Accuracy: 0.948
F1 Score: 0.951
Precision: 0.940
Recall: 0.962
After Cross Validation:
Accuracy: 95.27 %
Standard Deviation: 2.29 %


In [27]:
run_kernel_SVM(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.8405600225512436
Test set
Kernel SVM roc-auc: 0.8537986186841149
Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.73      0.79       350
         1.0       0.78      0.89      0.83       393

    accuracy                           0.81       743
   macro avg       0.82      0.81      0.81       743
weighted avg       0.82      0.81      0.81       743

Confusion Matrix:
[[254  96]
 [ 43 350]]
Metrics:
Accuracy: 0.813
F1 Score: 0.834
Precision: 0.785
Recall: 0.891
After Cross Validation:
Accuracy: 78.83 %
Standard Deviation: 3.81 %


In [28]:
run_knn(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
KNN roc-auc: 0.5
Test set
KNN roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.82      0.85       350
         1.0       0.85      0.91      0.88       393

    accuracy                           0.87       743
   macro avg       0.87      0.86      0.87       743
weighted avg       0.87      0.87      0.87       743

Confusion Matrix:
[[286  64]
 [ 35 358]]
Metrics:
Accuracy: 0.867
F1 Score: 0.879
Precision: 0.848
Recall: 0.911
After Cross Validation:
Accuracy: 85.98 %
Standard Deviation: 2.23 %


In [29]:
run_decision_tree(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.8776590330788805
Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.88      0.87       350
         1.0       0.89      0.88      0.88       393

    accuracy                           0.88       743
   macro avg       0.88      0.88      0.88       743
weighted avg       0.88      0.88      0.88       743

Confusion Matrix:
[[308  42]
 [ 49 344]]
Metrics:
Accuracy: 0.878
F1 Score: 0.883
Precision: 0.891
Recall: 0.875
After Cross Validation:
Accuracy: 89.10 %
Standard Deviation: 2.20 %


In [ ]:
run_linear_SVM(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.91      0.93       350
         1.0       0.92      0.97      0.94       393

    accuracy                           0.94       743
   macro avg       0.94      0.94      0.94       743
weighted avg       0.94      0.94      0.94       743

Confusion Matrix:
[[317  33]
 [ 13 380]]
Metrics:
Accuracy: 0.938
F1 Score: 0.943
Precision: 0.920
Recall: 0.967
After Cross Validation:


In [30]:
run_naive_bayes(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.89      0.88       350
         1.0       0.90      0.88      0.89       393

    accuracy                           0.89       743
   macro avg       0.89      0.89      0.89       743
weighted avg       0.89      0.89      0.89       743

Confusion Matrix:
[[312  38]
 [ 46 347]]
Metrics:
Accuracy: 0.887
F1 Score: 0.892
Precision: 0.901
Recall: 0.883
After Cross Validation:
Accuracy: 87.60 %
Standard Deviation: 2.95 %
