In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold, f_classif, SelectKBest

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import roc_auc_score

In [2]:
data = pd.read_csv('image_bins_stats.csv')
data.shape

(24000, 98)

In [3]:
data.head()

filename  rmean_bins0  rmean_bins1  rmean_bins2  rmean_bins3  \
0  clean_p_1.jpg     1.485688   116.416667          0.0          0.0   
1  clean_p_2.jpg     0.191129    91.000000          0.0          0.0   
2  clean_p_3.jpg     1.218065   115.000000          0.0          0.0   
3  clean_p_4.jpg     0.148524    98.000000          0.0          0.0   
4  clean_p_5.jpg     0.183128     0.000000          0.0          0.0   

   rmean_bins4  rmean_bins5  rmean_bins6  rmean_bins7  rstd_bins0  ...  \
0     0.000000   128.758621          0.0   159.770015   11.472993  ...   
1     0.000000   122.485714          0.0   149.839854    0.626280  ...   
2   121.730769   135.517857          0.0   154.189458   10.132966  ...   
3     0.000000   129.906667          0.0   157.583812    0.573290  ...   
4     0.000000     0.000000          0.0   158.600042    0.602004  ...   

   bskew_bins7  bkurto_bins0  bkurto_bins1  bkurto_bins2  bkurto_bins3  \
0     7.358843     47.621590      3.092351           0.0           0.0   
1     8.430080      7.154429      0.840896           0.0           0.0   
2     7.949709     43.394240      0.420448           0.0           0.0   
3     8.987692      6.601182      2.619225           0.0           0.0   
4     7.204324      6.869720      0.000000           0.0           0.0   

   bkurto_bins4  bkurto_bins5  bkurto_bins6  bkurto_bins7  class  
0      0.000000      8.421707           0.0      9.181035      1  
1      0.000000     15.029039           0.0     10.516990      1  
2      7.701832     13.599319           0.0     10.354453      1  
3      0.000000     12.787280           0.0     10.943418      1  
4      0.000000      0.000000           0.0      8.924785      1  

[5 rows x 98 columns]

In [4]:
data = data.drop(['filename'], axis=1)
data.head()

rmean_bins0  rmean_bins1  rmean_bins2  rmean_bins3  rmean_bins4  \
0     1.485688   116.416667          0.0          0.0     0.000000   
1     0.191129    91.000000          0.0          0.0     0.000000   
2     1.218065   115.000000          0.0          0.0   121.730769   
3     0.148524    98.000000          0.0          0.0     0.000000   
4     0.183128     0.000000          0.0          0.0     0.000000   

   rmean_bins5  rmean_bins6  rmean_bins7  rstd_bins0  rstd_bins1  ...  \
0   128.758621          0.0   159.770015   11.472993    1.943118  ...   
1   122.485714          0.0   149.839854    0.626280    0.000000  ...   
2   135.517857          0.0   154.189458   10.132966    0.000000  ...   
3   129.906667          0.0   157.583812    0.573290    2.000000  ...   
4     0.000000          0.0   158.600042    0.602004    0.000000  ...   

   bskew_bins7  bkurto_bins0  bkurto_bins1  bkurto_bins2  bkurto_bins3  \
0     7.358843     47.621590      3.092351           0.0           0.0   
1     8.430080      7.154429      0.840896           0.0           0.0   
2     7.949709     43.394240      0.420448           0.0           0.0   
3     8.987692      6.601182      2.619225           0.0           0.0   
4     7.204324      6.869720      0.000000           0.0           0.0   

   bkurto_bins4  bkurto_bins5  bkurto_bins6  bkurto_bins7  class  
0      0.000000      8.421707           0.0      9.181035      1  
1      0.000000     15.029039           0.0     10.516990      1  
2      7.701832     13.599319           0.0     10.354453      1  
3      0.000000     12.787280           0.0     10.943418      1  
4      0.000000      0.000000           0.0      8.924785      1  

[5 rows x 97 columns]

In [5]:
import numpy as np
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(data)

rmean_bins0  rmean_bins1  rmean_bins2  rmean_bins3  rmean_bins4  \
0         1.485688   116.416667          0.0          0.0     0.000000   
1         0.191129    91.000000          0.0          0.0     0.000000   
2         1.218065   115.000000          0.0          0.0   121.730769   
3         0.148524    98.000000          0.0          0.0     0.000000   
4         0.183128     0.000000          0.0          0.0     0.000000   
...            ...          ...          ...          ...          ...   
23994     0.167535     0.000000          0.0          0.0     0.000000   
23995     0.182460     0.000000          0.0          0.0     0.000000   
23996     0.222222     0.000000          0.0          0.0     0.000000   
23997     0.217425     0.000000          0.0          0.0     0.000000   
23998     0.226175     0.000000          0.0          0.0     0.000000   

       rmean_bins5  rmean_bins6  rmean_bins7  rstd_bins0  rstd_bins1  ...  \
0       128.758621     0.000000   159.770015   11.472993    1.943118  ...   
1       122.485714     0.000000   149.839854    0.626280    0.000000  ...   
2       135.517857     0.000000   154.189458   10.132966    0.000000  ...   
3       129.906667     0.000000   157.583812    0.573290    2.000000  ...   
4         0.000000     0.000000   158.600042    0.602004    0.000000  ...   
...            ...          ...          ...         ...         ...  ...   
23994     0.000000     0.000000   145.580835    0.587364    0.000000  ...   
23995     0.000000     0.000000   142.290042    0.590877    0.000000  ...   
23996     0.000000     0.000000   145.978772    0.689536    0.000000  ...   
23997     0.000000     0.000000   145.915418    0.665380    0.000000  ...   
23998     0.000000   114.428571   144.317780    0.689573    0.000000  ...   

       bskew_bins7  bkurto_bins0  bkurto_bins1  bkurto_bins2  bkurto_bins3  \
0         7.358843     47.621590      3.092351           0.0           0.0   
1         8.430080      7.154429      0.840896           0.0           0.0   
2         7.949709     43.394240      0.420448           0.0           0.0   
3         8.987692      6.601182      2.619225           0.0           0.0   
4         7.204324      6.869720      0.000000           0.0           0.0   
...            ...           ...           ...           ...           ...   
23994     6.817875      7.277478      0.000000           0.0           0.0   
23995     5.262551      8.170191      0.000000           0.0           0.0   
23996     5.407731      7.859719      0.000000           0.0           0.0   
23997     5.073114      7.887594      0.000000           0.0           0.0   
23998     7.435542      7.406609      0.000000           0.0           0.0   

       bkurto_bins4  bkurto_bins5  bkurto_bins6  bkurto_bins7  class  
0          0.000000      8.421707      0.000000      9.181035    1.0  
1          0.000000     15.029039      0.000000     10.516990    1.0  
2          7.701832     13.599319      0.000000     10.354453    1.0  
3          0.000000     12.787280      0.000000     10.943418    1.0  
4          0.000000      0.000000      0.000000      8.924785    1.0  
...             ...           ...           ...           ...    ...  
23994      0.000000      0.000000      0.000000     11.111529    0.0  
23995      0.000000      0.000000      0.000000     10.111068    0.0  
23996      0.000000      0.000000      0.000000      9.734824    0.0  
23997      0.000000      0.000000      0.000000      9.672132    0.0  
23998      0.000000      0.000000     14.278229     11.305344    0.0  

[23999 rows x 97 columns]

In [6]:
# separate train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    data.drop(labels=['class'], axis=1),
    data['class'],
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((16799, 96), (7200, 96))

In [7]:
# I keep a copy of the dataset with all the variables
# to compare the performance of machine learning models
# at the end of the notebook

X_train_original = X_train.copy()
X_test_original = X_test.copy()

In [8]:
# find and remove correlated features
def correlation(dataset, threshold):
    
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            # we are interested in absolute coeff value
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)
    
    return col_corr


corr_features = correlation(X_train, 0.8)
print('correlated features: ', len(set(corr_features)))

correlated features:  72


In [9]:
# remove correlated features
X_train.drop(labels=corr_features, axis=1, inplace=True)
X_test.drop(labels=corr_features, axis=1, inplace=True)

X_train.shape, X_test.shape

((16799, 24), (7200, 24))

In [10]:
# keep a copy of the dataset at  this stage
X_train_corr = X_train.copy()
X_test_corr = X_test.copy()

In [11]:
sel_ = SelectKBest(f_classif, k=20).fit(X_train, y_train)

# capture selected feature names
features_to_keep = X_train.columns[sel_.get_support()]

# select features
X_train_anova = sel_.transform(X_train)
X_test_anova = sel_.transform(X_test)

# numpy array to dataframe
X_train_anova = pd.DataFrame(X_train_anova)
X_train_anova.columns = features_to_keep

X_test_anova = pd.DataFrame(X_test_anova)
X_test_anova.columns = features_to_keep

X_train_anova.shape, X_test_anova.shape

((16799, 20), (7200, 20))

In [12]:
# create a function to build random forests and
# compare its performance in train and test sets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
import scikitplot as skplt
import matplotlib.pyplot as plt

def run_randomForests(X_train, X_test, y_train, y_test):
    
    rf = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
    rf.fit(X_train, y_train)
    
    print('Train set')
    pred = rf.predict_proba(X_train)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = rf.predict_proba(X_test)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    y_pred = rf.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [16]:
run_randomForests(X_train_original,
                  X_test_original,
                  y_train, y_test)

Train set
Random Forests roc-auc: 0.9986183833413939
Test set
Random Forests roc-auc: 0.998528358500821
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.98      0.96      3559
           1       0.98      0.94      0.96      3641

    accuracy                           0.96      7200
   macro avg       0.96      0.96      0.96      7200
weighted avg       0.96      0.96      0.96      7200

Confusion Matrix:
[[3501   58]
 [ 211 3430]]
Metrics:
Accuracy: 0.963
F1 Score: 0.962
Precision: 0.983
Recall: 0.942
After Cross Validation:
Accuracy: 96.58 %
Standard Deviation: 0.55 %


In [13]:
# filter methods - univariate roc-auc
run_randomForests(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
Random Forests roc-auc: 0.9721790132836361
Test set
Random Forests roc-auc: 0.9717366504096713
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      3559
           1       0.97      0.93      0.95      3641

    accuracy                           0.95      7200
   macro avg       0.95      0.95      0.95      7200
weighted avg       0.95      0.95      0.95      7200

Confusion Matrix:
[[3468   91]
 [ 244 3397]]
Metrics:
Accuracy: 0.953
F1 Score: 0.953
Precision: 0.974
Recall: 0.933
After Cross Validation:
Accuracy: 95.35 %
Standard Deviation: 0.64 %


In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

def run_logistic(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    logit = LogisticRegression(penalty='l1', random_state=44, max_iter=1000, solver='liblinear')
    logit.fit(X_train, y_train)
    
    print('Train set')
    pred = logit.predict_proba(scaler.transform(X_train))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = logit.predict_proba(scaler.transform(X_test))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = logit.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = logit, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [15]:
run_logistic(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
Logistic Regression roc-auc: 0.49073044123625303
Test set
Logistic Regression roc-auc: 0.5013979050832132
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      3559
           1       0.97      0.93      0.95      3641

    accuracy                           0.95      7200
   macro avg       0.95      0.95      0.95      7200
weighted avg       0.95      0.95      0.95      7200

Confusion Matrix:
[[3459  100]
 [ 243 3398]]
Metrics:
Accuracy: 0.952
F1 Score: 0.952
Precision: 0.971
Recall: 0.933
After Cross Validation:
Accuracy: 95.22 %
Standard Deviation: 0.60 %


In [17]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_kernel_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [19]:
run_kernel_SVM(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
Kernel SVM roc-auc: 0.9634873357830394
Test set
Kernel SVM roc-auc: 0.9623356239339378
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      3559
           1       0.97      0.94      0.95      3641

    accuracy                           0.95      7200
   macro avg       0.96      0.95      0.95      7200
weighted avg       0.96      0.95      0.95      7200

Confusion Matrix:
[[3465   94]
 [ 233 3408]]
Metrics:
Accuracy: 0.955
F1 Score: 0.954
Precision: 0.973
Recall: 0.936
After Cross Validation:
Accuracy: 95.43 %
Standard Deviation: 0.67 %


In [20]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.neighbors import KNeighborsClassifier

def run_knn(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [21]:
run_knn(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
KNN roc-auc: 0.5
Test set
KNN roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.97      0.96      3559
           1       0.97      0.94      0.96      3641

    accuracy                           0.96      7200
   macro avg       0.96      0.96      0.96      7200
weighted avg       0.96      0.96      0.96      7200

Confusion Matrix:
[[3466   93]
 [ 220 3421]]
Metrics:
Accuracy: 0.957
F1 Score: 0.956
Precision: 0.974
Recall: 0.940
After Cross Validation:
Accuracy: 95.48 %
Standard Deviation: 0.66 %


In [22]:
from sklearn.tree import DecisionTreeClassifier


def run_decision_tree(X_train, X_test, y_train, y_test):

    # function to train and test the performance of logistic regression
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(X_train)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(X_test)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [23]:
run_decision_tree(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.9312489914779841
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      3559
           1       0.93      0.93      0.93      3641

    accuracy                           0.93      7200
   macro avg       0.93      0.93      0.93      7200
weighted avg       0.93      0.93      0.93      7200

Confusion Matrix:
[[3314  245]
 [ 250 3391]]
Metrics:
Accuracy: 0.931
F1 Score: 0.932
Precision: 0.933
Recall: 0.931
After Cross Validation:
Accuracy: 93.08 %
Standard Deviation: 0.28 %


In [24]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.naive_bayes import GaussianNB

def run_naive_bayes(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [25]:
run_naive_bayes(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
Kernel SVM roc-auc: 0.6531536658560827
Test set
Kernel SVM roc-auc: 0.6435440044345259
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90      3559
           1       0.94      0.85      0.89      3641

    accuracy                           0.90      7200
   macro avg       0.90      0.90      0.90      7200
weighted avg       0.90      0.90      0.90      7200

Confusion Matrix:
[[3345  214]
 [ 535 3106]]
Metrics:
Accuracy: 0.896
F1 Score: 0.892
Precision: 0.936
Recall: 0.853
After Cross Validation:
Accuracy: 90.04 %
Standard Deviation: 0.70 %


In [26]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_linear_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'linear', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
run_linear_SVM(X_train_anova,
                  X_test_anova,
                  y_train, y_test)

Train set
Kernel SVM roc-auc: 0.8707746963995444
Test set
Kernel SVM roc-auc: 0.8819914064470862
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      3559
           1       0.97      0.93      0.95      3641

    accuracy                           0.95      7200
   macro avg       0.95      0.95      0.95      7200
weighted avg       0.95      0.95      0.95      7200

Confusion Matrix:
[[3468   91]
 [ 247 3394]]
Metrics:
Accuracy: 0.953
F1 Score: 0.953
Precision: 0.974
Recall: 0.932
After Cross Validation:
