In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('image_bins_stats_lungs2.csv')
data.shape

(2696, 106)

In [3]:
data.head()

filename   Bins0    Bins1  Bins2    Bins3    Bins4  \
0  transformed_image_normal_1.png  5822.0  14402.0    0.0   9189.0  10538.0   
1  transformed_image_normal_2.png  6325.0  11758.0    0.0  10893.0  13314.0   
2  transformed_image_normal_3.png  5911.0  15666.0    0.0   9025.0  13587.0   
3  transformed_image_normal_4.png  5688.0  15515.0    0.0   8941.0  10462.0   
4  transformed_image_normal_5.png  6101.0  12231.0    0.0  10258.0  14797.0   

   Bins5    Bins6    Bins7  rmean_bins0  ...  bskew_bins7  bkurto_bins0  \
0    0.0  11831.0  13754.0    86.982480  ...   30.9217012     27.556681   
1    0.0   8460.0  14786.0    86.937708  ...  32.45653958     30.429971   
2    0.0   8205.0  13142.0    76.833362  ...  32.04297751     31.149385   
3    0.0  11009.0  13921.0    73.869726  ...  29.69319943     31.537897   
4    0.0   7655.0  14494.0    87.165219  ...  32.21430004     31.326113   

   bkurto_bins1  bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5  \
0     26.125116           0.0     12.668177     19.678833           0.0   
1     21.410499           0.0      9.701043     16.311605           0.0   
2     23.374875           0.0     12.936013     17.187983           0.0   
3     22.614153           0.0     11.457708     15.659193           0.0   
4     21.152459           0.0     12.285766     13.344069           0.0   

  bkurto_bins6 bkurto_bins7 class  
0    42.325143    33.029938     1  
1    41.183742    36.344060     1  
2    45.580706    35.631835     1  
3    42.081886    32.843335     1  
4    42.956341    36.139280     1  

[5 rows x 106 columns]

In [4]:
data = data.drop(['filename'], axis=1)
data.head()

Bins0    Bins1  Bins2    Bins3    Bins4  Bins5    Bins6    Bins7  \
0  5822.0  14402.0    0.0   9189.0  10538.0    0.0  11831.0  13754.0   
1  6325.0  11758.0    0.0  10893.0  13314.0    0.0   8460.0  14786.0   
2  5911.0  15666.0    0.0   9025.0  13587.0    0.0   8205.0  13142.0   
3  5688.0  15515.0    0.0   8941.0  10462.0    0.0  11009.0  13921.0   
4  6101.0  12231.0    0.0  10258.0  14797.0    0.0   7655.0  14494.0   

   rmean_bins0  rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0    86.982480     4.430912  ...   30.9217012     27.556681     26.125116   
1    86.937708     5.183279  ...  32.45653958     30.429971     21.410499   
2    76.833362     2.389570  ...  32.04297751     31.149385     23.374875   
3    73.869726     1.710925  ...  29.69319943     31.537897     22.614153   
4    87.165219     5.596517  ...  32.21430004     31.326113     21.152459   

   bkurto_bins2  bkurto_bins3  bkurto_bins4 bkurto_bins5 bkurto_bins6  \
0           0.0     12.668177     19.678833          0.0    42.325143   
1           0.0      9.701043     16.311605          0.0    41.183742   
2           0.0     12.936013     17.187983          0.0    45.580706   
3           0.0     11.457708     15.659193          0.0    42.081886   
4           0.0     12.285766     13.344069          0.0    42.956341   

  bkurto_bins7 class  
0    33.029938     1  
1    36.344060     1  
2    35.631835     1  
3    32.843335     1  
4    36.139280     1  

[5 rows x 105 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2696 entries, 0 to 2695
Columns: 105 entries, Bins0 to class
dtypes: float64(56), object(49)
memory usage: 2.2+ MB


In [6]:
name = ['rstd_bins0','rstd_bins1','rstd_bins2','rstd_bins3','rstd_bins4','rstd_bins5','rstd_bins6','rstd_bins7','rskew_bins0','rskew_bins1','rskew_bins2','rskew_bins3','rskew_bins4','rskew_bins5','rskew_bins6','rskew_bins7','gstd_bins0','gstd_bins1','gstd_bins2','gstd_bins3','gstd_bins4','gstd_bins5','gstd_bins6','gstd_bins7','bstd_bins0','bstd_bins1','bstd_bins2','bstd_bins3','bstd_bins4','bstd_bins5','bstd_bins6','bstd_bins7','gskew_bins0','gskew_bins1','gskew_bins2','gskew_bins3','gskew_bins4','gskew_bins5','gskew_bins6','gskew_bins7','bskew_bins0','bskew_bins1','bskew_bins2','bskew_bins3','bskew_bins4','bskew_bins5','bskew_bins6','bskew_bins7','class']
for i in name:
    data[i] = pd.to_numeric(data[i],errors='coerce')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2696 entries, 0 to 2695
Columns: 105 entries, Bins0 to class
dtypes: float64(105)
memory usage: 2.2 MB


In [8]:
import numpy as np
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(data)

Bins0    Bins1  Bins2    Bins3    Bins4  Bins5    Bins6    Bins7  \
0     5822.0  14402.0    0.0   9189.0  10538.0    0.0  11831.0  13754.0   
1     6325.0  11758.0    0.0  10893.0  13314.0    0.0   8460.0  14786.0   
2     5911.0  15666.0    0.0   9025.0  13587.0    0.0   8205.0  13142.0   
3     5688.0  15515.0    0.0   8941.0  10462.0    0.0  11009.0  13921.0   
4     6101.0  12231.0    0.0  10258.0  14797.0    0.0   7655.0  14494.0   
...      ...      ...    ...      ...      ...    ...      ...      ...   
2689  9870.0  10436.0   13.0   9558.0   9764.0    0.0  16080.0   9815.0   
2690  5946.0  14026.0    1.0  11041.0  12415.0    0.0   7886.0  14221.0   
2691  7330.0   8408.0    6.0  10811.0  18521.0    2.0   6699.0  13759.0   
2692  7630.0  16431.0    1.0   9530.0   3413.0    3.0  17843.0  10685.0   
2693  5415.0  17347.0    0.0   8790.0  12865.0    2.0   8924.0  12193.0   

      rmean_bins0  rmean_bins1  ...  bskew_bins7  bkurto_bins0  bkurto_bins1  \
0       86.982480     4.430912  ...    30.921701     27.556681     26.125116   
1       86.937708     5.183279  ...    32.456540     30.429971     21.410499   
2       76.833362     2.389570  ...    32.042978     31.149385     23.374875   
3       73.869726     1.710925  ...    29.693199     31.537897     22.614153   
4       87.165219     5.596517  ...    32.214300     31.326113     21.152459   
...           ...          ...  ...          ...           ...           ...   
2689   104.708207    27.440974  ...    28.826381     16.609479     32.541509   
2690    74.044736     1.607016  ...    39.246127     30.936390     21.337923   
2691   112.515416     7.136774  ...    28.790502     42.515393     18.625921   
2692    73.122412    24.310145  ...    37.426827     20.622111     29.148814   
2693    60.702862     1.042082  ...    34.588816     33.378388     26.261638   

      bkurto_bins2  bkurto_bins3  bkurto_bins4  bkurto_bins5  bkurto_bins6  \
0         0.000000     12.668177     19.678833      0.000000     42.325143   
1         0.000000      9.701043     16.311605      0.000000     41.183742   
2         0.000000     12.936013     17.187983      0.000000     45.580706   
3         0.000000     11.457708     15.659193      0.000000     42.081886   
4         0.000000     12.285766     13.344069      0.000000     42.956341   
...            ...           ...           ...           ...           ...   
2689     10.841782     18.263777     29.591836      0.000000     43.584547   
2690      0.000000      9.706518     17.877323      0.000000     45.339391   
2691     11.891740     14.170267      3.991819      0.000000     36.311970   
2692      0.000000     20.197666     31.678731      4.769168     50.967873   
2693      0.000000     17.291031     20.163037      5.045378     45.099627   

      bkurto_bins7  class  
0        33.029938    1.0  
1        36.344060    1.0  
2        35.631835    1.0  
3        32.843335    1.0  
4        36.139280    1.0  
...            ...    ...  
2689     43.219779    2.0  
2690     32.611797    2.0  
2691     41.914116    2.0  
2692     38.781249    2.0  
2693     35.944590    2.0  

[2683 rows x 105 columns]

In [9]:
# separate train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    data.drop(labels=['class'], axis=1),
    data['class'],
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((1878, 104), (805, 104))

In [10]:
# linear models benefit from feature scaling

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [18]:
# here I will do the model fitting and feature selection
# altogether in one line of code

# first I specify the Logistic Regression model, and I
# make sure I select the Lasso (l1) penalty.

# Then I use the selectFromModel class from sklearn, which
# will select the features which coefficients are non-zero

sel_ = SelectFromModel(
    LogisticRegression(C=0.07, penalty='l1', solver='liblinear', random_state=10))

sel_.fit(scaler.transform(X_train), y_train)

SelectFromModel(estimator=LogisticRegression(C=0.07, penalty='l1',
                                             random_state=10,
                                             solver='liblinear'))

In [19]:
# this command let's me visualise the index of the
# features that were selected

sel_.get_support()

array([False, False, False, False, False,  True, False, False,  True,
        True,  True, False,  True,  True, False,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True, False,
       False,  True,  True, False, False,  True, False, False, False,
        True, False, False, False,  True,  True, False, False,  True,
        True, False, False,  True, False,  True,  True,  True, False,
       False, False,  True, False, False,  True, False,  True, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False, False, False,  True, False, False,  True, False,  True,
       False,  True,  True, False,  True, False, False,  True, False,
       False, False, False, False, False, False,  True, False,  True,
        True,  True, False, False,  True])

In [20]:
# Now I make a list with the selected features
selected_feat = X_train.columns[(sel_.get_support())]

print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(sel_.estimator_.coef_ == 0)))

total features: 104
selected features: 44
features with coefficients shrank to zero: 60


In [21]:
# the number of features which coefficient was shrank to zero:
np.sum(sel_.estimator_.coef_ == 0)

60

In [22]:
# we can identify the removed features like this:

removed_feats = X_train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

Index(['Bins0', 'Bins1', 'Bins2', 'Bins3', 'Bins4', 'Bins6', 'Bins7',
       'rmean_bins3', 'rmean_bins6', 'rstd_bins1', 'rstd_bins2', 'rstd_bins3',
       'rstd_bins6', 'rskew_bins2', 'rskew_bins3', 'rskew_bins6',
       'rskew_bins7', 'rkurto_bins1', 'rkurto_bins2', 'rkurto_bins3',
       'rkurto_bins5', 'rkurto_bins6', 'rkurto_bins7', 'gmean_bins2',
       'gmean_bins3', 'gmean_bins6', 'gmean_bins7', 'gstd_bins1', 'gstd_bins5',
       'gstd_bins6', 'gstd_bins7', 'gskew_bins1', 'gskew_bins2', 'gskew_bins4',
       'gskew_bins6', 'gskew_bins7', 'gkurto_bins4', 'gkurto_bins5',
       'gkurto_bins6', 'gkurto_bins7', 'bmean_bins0', 'bmean_bins1',
       'bmean_bins2', 'bmean_bins4', 'bmean_bins5', 'bmean_bins7',
       'bstd_bins1', 'bstd_bins4', 'bstd_bins6', 'bstd_bins7', 'bskew_bins1',
       'bskew_bins2', 'bskew_bins3', 'bskew_bins4', 'bskew_bins5',
       'bskew_bins6', 'bskew_bins7', 'bkurto_bins1', 'bkurto_bins5',
       'bkurto_bins6'],
      dtype='object')

In [23]:
# we can then remove the features from the training and testing set
# like this:

X_train_selected = sel_.transform(X_train)
X_test_selected = sel_.transform(X_test)

X_train_selected.shape, X_test_selected.shape

((1878, 44), (805, 44))

In [24]:
selected_features = X_train.columns

In [25]:
# create a function to build random forests and
# compare its performance in train and test sets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score, mean_squared_error
import scikitplot as skplt
import matplotlib.pyplot as plt

def run_randomForests(X_train, X_test, y_train, y_test):
    
    rf = RandomForestClassifier(n_estimators=200, random_state=39, max_depth=4)
    rf.fit(X_train, y_train)
    
    print('Train set')
    pred = rf.predict_proba(X_train)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = rf.predict_proba(X_test)
    print('Random Forests roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    y_pred = rf.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [26]:
run_randomForests(X_train_selected, X_test_selected, y_train, y_test)

Train set
Random Forests roc-auc: 0.9136399210562133
Test set
Random Forests roc-auc: 0.8921904514982038
Classification Report:
              precision    recall  f1-score   support

         1.0       0.79      0.87      0.83       406
         2.0       0.85      0.77      0.81       399

    accuracy                           0.82       805
   macro avg       0.82      0.82      0.82       805
weighted avg       0.82      0.82      0.82       805

Confusion Matrix:
[[353  53]
 [ 93 306]]
Metrics:
Accuracy: 0.819
F1 Score: 0.829
Precision: 0.791
Recall: 0.869
After Cross Validation:
Accuracy: 81.09 %
Standard Deviation: 3.76 %


In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

def run_logistic(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    logit = LogisticRegression(penalty='l1', random_state=44, max_iter=1000, solver='liblinear')
    logit.fit(X_train, y_train)
    
    print('Train set')
    pred = logit.predict_proba(scaler.transform(X_train))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = logit.predict_proba(scaler.transform(X_test))
    print('Logistic Regression roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = logit.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = logit, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [21]:
run_logistic(X_train_selected, X_test_selected, y_train, y_test)

Train set
Logistic Regression roc-auc: 0.682251259017286
Test set
Logistic Regression roc-auc: 0.6765806140968184
Classification Report:
              precision    recall  f1-score   support

         1.0       0.84      0.88      0.86       406
         2.0       0.87      0.83      0.85       399

    accuracy                           0.86       805
   macro avg       0.86      0.86      0.86       805
weighted avg       0.86      0.86      0.86       805

Confusion Matrix:
[[358  48]
 [ 68 331]]
Metrics:
Accuracy: 0.856
F1 Score: 0.861
Precision: 0.840
Recall: 0.882
After Cross Validation:
Accuracy: 83.92 %
Standard Deviation: 2.99 %


In [22]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_kernel_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [23]:
run_kernel_SVM(X_train_selected, X_test_selected, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.7850358422939068
Test set
Kernel SVM roc-auc: 0.8106349617887082
Classification Report:
              precision    recall  f1-score   support

         1.0       0.75      0.82      0.78       406
         2.0       0.80      0.71      0.75       399

    accuracy                           0.77       805
   macro avg       0.77      0.77      0.77       805
weighted avg       0.77      0.77      0.77       805

Confusion Matrix:
[[334  72]
 [114 285]]
Metrics:
Accuracy: 0.769
F1 Score: 0.782
Precision: 0.746
Recall: 0.823
After Cross Validation:
Accuracy: 74.33 %
Standard Deviation: 3.04 %


In [24]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.neighbors import KNeighborsClassifier

def run_knn(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('KNN roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [25]:
run_knn(X_train_selected, X_test_selected, y_train, y_test)

Train set
KNN roc-auc: 0.5
Test set
KNN roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         1.0       0.72      0.93      0.81       406
         2.0       0.90      0.64      0.75       399

    accuracy                           0.79       805
   macro avg       0.81      0.78      0.78       805
weighted avg       0.81      0.79      0.78       805

Confusion Matrix:
[[377  29]
 [144 255]]
Metrics:
Accuracy: 0.785
F1 Score: 0.813
Precision: 0.724
Recall: 0.929
After Cross Validation:
Accuracy: 78.01 %
Standard Deviation: 4.39 %


In [26]:
from sklearn.tree import DecisionTreeClassifier


def run_decision_tree(X_train, X_test, y_train, y_test):

    # function to train and test the performance of logistic regression
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(X_train)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(X_test)
    print('Decision Tree roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [27]:
run_decision_tree(X_train_selected, X_test_selected, y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.7850229020827932
Classification Report:
              precision    recall  f1-score   support

         1.0       0.78      0.79      0.79       406
         2.0       0.79      0.78      0.78       399

    accuracy                           0.79       805
   macro avg       0.79      0.79      0.79       805
weighted avg       0.79      0.79      0.79       805

Confusion Matrix:
[[322  84]
 [ 89 310]]
Metrics:
Accuracy: 0.785
F1 Score: 0.788
Precision: 0.783
Recall: 0.793
After Cross Validation:
Accuracy: 77.31 %
Standard Deviation: 2.85 %


In [28]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.svm import SVC

def run_linear_SVM(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = SVC(kernel = 'linear', random_state = 0, probability=True)
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
run_linear_SVM(X_train_selected, X_test_selected, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         1.0       0.83      0.90      0.87       406
         2.0       0.89      0.82      0.85       399

    accuracy                           0.86       805
   macro avg       0.86      0.86      0.86       805
weighted avg       0.86      0.86      0.86       805

Confusion Matrix:
[[367  39]
 [ 73 326]]
Metrics:
Accuracy: 0.861
F1 Score: 0.868
Precision: 0.834
Recall: 0.904
After Cross Validation:


In [ ]:
# create a function to build logistic regression
# and compare its performance in train and test sets
from sklearn.naive_bayes import GaussianNB

def run_naive_bayes(X_train, X_test, y_train, y_test):
    
    scaler = StandardScaler().fit(X_train)
    
    # function to train and test the performance of logistic regression
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    
    print('Train set')
    pred = classifier.predict_proba(scaler.transform(X_train))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_train, pred[:,1])))
    
    print('Test set')
    pred = classifier.predict_proba(scaler.transform(X_test))
    print('Kernel SVM roc-auc: {}'.format(roc_auc_score(y_test, pred[:,1])))
    
    y_pred = classifier.predict(X_test)
    
    print('Classification Report:')
    print(classification_report(y_test, y_pred))
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_test, y_pred))
    
    print('Metrics:')
    print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
    print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
    print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
    print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
    
    print('After Cross Validation:')
    accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [ ]:
run_naive_bayes(X_train_selected, X_test_selected, y_train, y_test)

In [11]:
# For comparison, I will fit a logistic regression with a
# Ridge regularisation, and evaluate the coefficients

l1_logit = LogisticRegression(C=0.5, penalty='l2', max_iter=300, random_state=10)
l1_logit.fit(scaler.transform(X_train), y_train)

# I count the number of coefficients with zero values
# and it is zero, as expected
np.sum(l1_logit.coef_ == 0)

0

In [12]:
# here I will do the model fitting and feature selection
# altogether in one line of code

# first I specify the Logistic Regression model, and I
# make sure I select the Lasso (l1) penalty.

# Then I use the selectFromModel class from sklearn, which
# will select the features which coefficients are non-zero

sel_ = SelectFromModel(
    LogisticRegression(C=0.5, penalty='l2', solver='liblinear', random_state=10))

sel_.fit(scaler.transform(X_train), y_train)

SelectFromModel(estimator=LogisticRegression(C=0.5, random_state=10,
                                             solver='liblinear'))

In [13]:
# this command let's me visualise the index of the
# features that were selected

sel_.get_support()

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False, False, False,  True,  True, False, False, False, False,
       False,  True,  True, False,  True,  True, False, False, False,
        True,  True, False,  True, False,  True,  True, False, False,
        True, False,  True,  True,  True, False, False,  True, False,
        True, False, False,  True, False, False,  True, False, False,
        True,  True, False, False, False, False, False, False,  True,
        True,  True, False, False, False, False, False,  True, False,
       False,  True, False,  True, False,  True, False, False,  True,
        True, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False])

In [14]:
# Now I make a list with the selected features
selected_feat = X_train.columns[(sel_.get_support())]

print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(sel_.estimator_.coef_ == 0)))

total features: 104
selected features: 41
features with coefficients shrank to zero: 0


In [15]:
# we can identify the removed features like this:

removed_feats = X_train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

Index([], dtype='object')

In [16]:
# we can then remove the features from the training and testing set
# like this:

X_train_ridge = sel_.transform(X_train)
X_test_ridge = sel_.transform(X_test)

X_train_ridge.shape, X_test_ridge.shape

((1733, 41), (743, 41))

In [25]:
run_randomForests(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Random Forests roc-auc: 0.9852007463387787
Test set
Random Forests roc-auc: 0.9729843693202471
Classification Report:
              precision    recall  f1-score   support

         0.0       0.93      0.90      0.91       350
         1.0       0.91      0.94      0.93       393

    accuracy                           0.92       743
   macro avg       0.92      0.92      0.92       743
weighted avg       0.92      0.92      0.92       743

Confusion Matrix:
[[315  35]
 [ 24 369]]
Metrics:
Accuracy: 0.921
F1 Score: 0.926
Precision: 0.913
Recall: 0.939
After Cross Validation:
Accuracy: 91.69 %
Standard Deviation: 1.78 %


In [26]:
run_logistic(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Logistic Regression roc-auc: 0.9265863054888117
Test set
Logistic Regression roc-auc: 0.9158197019265721
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.93      0.94       350
         1.0       0.94      0.96      0.95       393

    accuracy                           0.95       743
   macro avg       0.95      0.95      0.95       743
weighted avg       0.95      0.95      0.95       743

Confusion Matrix:
[[326  24]
 [ 15 378]]
Metrics:
Accuracy: 0.948
F1 Score: 0.951
Precision: 0.940
Recall: 0.962
After Cross Validation:
Accuracy: 95.27 %
Standard Deviation: 2.29 %


In [27]:
run_kernel_SVM(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.8405600225512436
Test set
Kernel SVM roc-auc: 0.8537986186841149
Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.73      0.79       350
         1.0       0.78      0.89      0.83       393

    accuracy                           0.81       743
   macro avg       0.82      0.81      0.81       743
weighted avg       0.82      0.81      0.81       743

Confusion Matrix:
[[254  96]
 [ 43 350]]
Metrics:
Accuracy: 0.813
F1 Score: 0.834
Precision: 0.785
Recall: 0.891
After Cross Validation:
Accuracy: 78.83 %
Standard Deviation: 3.81 %


In [28]:
run_knn(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
KNN roc-auc: 0.5
Test set
KNN roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.82      0.85       350
         1.0       0.85      0.91      0.88       393

    accuracy                           0.87       743
   macro avg       0.87      0.86      0.87       743
weighted avg       0.87      0.87      0.87       743

Confusion Matrix:
[[286  64]
 [ 35 358]]
Metrics:
Accuracy: 0.867
F1 Score: 0.879
Precision: 0.848
Recall: 0.911
After Cross Validation:
Accuracy: 85.98 %
Standard Deviation: 2.23 %


In [29]:
run_decision_tree(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Decision Tree roc-auc: 1.0
Test set
Decision Tree roc-auc: 0.8776590330788805
Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.88      0.87       350
         1.0       0.89      0.88      0.88       393

    accuracy                           0.88       743
   macro avg       0.88      0.88      0.88       743
weighted avg       0.88      0.88      0.88       743

Confusion Matrix:
[[308  42]
 [ 49 344]]
Metrics:
Accuracy: 0.878
F1 Score: 0.883
Precision: 0.891
Recall: 0.875
After Cross Validation:
Accuracy: 89.10 %
Standard Deviation: 2.20 %


In [ ]:
run_linear_SVM(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.91      0.93       350
         1.0       0.92      0.97      0.94       393

    accuracy                           0.94       743
   macro avg       0.94      0.94      0.94       743
weighted avg       0.94      0.94      0.94       743

Confusion Matrix:
[[317  33]
 [ 13 380]]
Metrics:
Accuracy: 0.938
F1 Score: 0.943
Precision: 0.920
Recall: 0.967
After Cross Validation:


In [30]:
run_naive_bayes(X_train_ridge, X_test_ridge, y_train, y_test)

Train set
Kernel SVM roc-auc: 0.5
Test set
Kernel SVM roc-auc: 0.5
Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.89      0.88       350
         1.0       0.90      0.88      0.89       393

    accuracy                           0.89       743
   macro avg       0.89      0.89      0.89       743
weighted avg       0.89      0.89      0.89       743

Confusion Matrix:
[[312  38]
 [ 46 347]]
Metrics:
Accuracy: 0.887
F1 Score: 0.892
Precision: 0.901
Recall: 0.883
After Cross Validation:
Accuracy: 87.60 %
Standard Deviation: 2.95 %
