In [1]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv('image_bins_all_color_GLCM.csv')

FileNotFoundError: [Errno 2] File image_bins_all_color_GLCM.csv does not exist: 'image_bins_all_color_GLCM.csv'

In [4]:
data.head()

Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7          var  \
0   5345     12      0      0      0     58      0  15601  2378.244684   
1   6582      2      0      0      0    130      0  13024  2231.711952   
2   7612      0      0      0     50    127      0  16419  2054.426557   
3   5145     12      0      0      0    259      0  13044  1567.735710   
4   4065      0      0      0      4    850      0   9815  1557.136176   

        asm     contrast  correlation       idm   entropy  homogenity  \
0  0.009158  1211.821712     0.797017  0.525642  7.810224    0.525642   
1  0.008901  1225.951925     0.784520  0.493865  7.915158    0.493865   
2  0.006830  1165.783478     0.778996  0.464011  8.416442    0.464011   
3  0.008009   668.185088     0.824332  0.499687  8.325647    0.499687   
4  0.004084   890.222724     0.777694  0.468373  9.291812    0.468373   

     energy  dissimilarity  Class  
0  0.095697       8.398868      1  
1  0.094346       8.767637      1  
2  0.082646       8.621760      1  
3  0.089494       6.199938      1  
4  0.063908       7.383222      1

In [5]:
# load data
dataframe = pd.read_csv('image_bins_GLCM_all.csv')

In [7]:
array = dataframe.values
X = array[:,0:28]
Y = array[:,28]

IndexError: index 29 is out of bounds for axis 1 with size 18

In [6]:
# Import the necessary libraries first
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [7]:
# Feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)

# Summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
# Summarize selected features
print(features[0:10,:])

[2.280e+05 6.680e+04 5.145e+01 1.179e+01 1.672e+05 2.023e+06 1.116e+03
 7.487e+03 3.382e+05 2.606e+00 1.287e+05 2.491e-02 1.688e+00 2.056e+02
 1.688e+00 6.529e+00 1.873e+02]
[[5.345e+03 0.000e+00 5.800e+01 2.378e+03]
 [6.582e+03 0.000e+00 1.300e+02 2.232e+03]
 [7.612e+03 5.000e+01 1.270e+02 2.054e+03]
 [5.145e+03 0.000e+00 2.590e+02 1.568e+03]
 [4.065e+03 4.000e+00 8.500e+02 1.557e+03]
 [4.029e+03 4.300e+01 1.101e+03 1.644e+03]
 [3.829e+03 1.400e+01 4.510e+02 2.068e+03]
 [3.211e+03 5.300e+01 2.820e+02 2.021e+03]
 [4.238e+03 8.000e+00 1.160e+02 1.943e+03]
 [4.158e+03 2.000e+00 2.550e+02 1.673e+03]]


In [8]:
# Import your necessary dependencies
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [12]:
# Feature extraction
model = LogisticRegression()
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

C:\Users\USER\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\USER\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regre

Num Features: 5
Selected Features: [False  True  True False False False False False False False False  True
 False  True False False  True]
Feature Ranking: [ 8  1  1  4  3  2  6  9  7 13  5  1 11  1 10 12  1]


In [14]:
# First things first
from sklearn.linear_model import Ridge

In [15]:
ridge = Ridge(alpha=1.0)
ridge.fit(X,Y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [18]:
# A helper method for pretty-printing the coefficients
def pretty_print_coefs(coefs, names = None, sort = False):
    if names == None:
        names = ["X%s" % x for x in range(len(coefs))]
    lst = zip(coefs, names)
    if sort:
        lst = sorted(lst,  key = lambda x:-np.abs(x[0]))
    return " + ".join("%s * %s" % (round(coef, 10), name)
                                   for coef, name in lst)

In [19]:
print ("Ridge model:", pretty_print_coefs(ridge.coef_))

Ridge model: 1.65523e-05 * X0 + -8.75427e-05 * X1 + -0.0197009645 * X2 + -0.0005203265 * X3 + 0.0016488248 * X4 + 0.00069402 * X5 + -0.0012679714 * X6 + -4.196e-06 * X7 + 0.0001894315 * X8 + 0.0094106488 * X9 + -0.0014035099 * X10 + -0.2527990382 * X11 + 1.287527473 * X12 + 0.5788583964 * X13 + 1.287527473 * X14 + 1.9711811772 * X15 + 0.2506973881 * X16
