# Support Vector Machine (SVM)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('image_bins_stats_gstd.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X = dataset.iloc[:, 1:].values

In [4]:
print(X)

[[5.55166942 7.1042564  0.         ... 0.         6.95121716 1.        ]
 [0.74706917 1.76776695 0.         ... 0.         6.87134466 1.        ]
 [6.25009374 4.24264069 0.         ... 0.         6.09665336 1.        ]
 ...
 [0.72078385 0.         0.         ... 0.         5.76324575 0.        ]
 [0.75751527 0.         0.         ... 6.96718098 9.12180953 0.        ]
 [0.82199739 0.         0.         ... 0.         5.62648158 0.        ]]


In [5]:
print(y)

[1 1 1 ... 0 0 0]


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
print(X_train)

[[ 0.62338297  0.          0.         ...  0.          7.43115602
   1.        ]
 [ 0.67496267  0.          0.         ...  0.          9.87011506
   0.        ]
 [ 0.67759696  0.          0.         ...  0.         12.54537173
   1.        ]
 ...
 [ 3.45355228 13.74031001  0.         ...  0.         16.93877191
   1.        ]
 [ 0.65400959  0.          0.         ...  0.          7.3686719
   1.        ]
 [ 8.53002288  6.54983977  0.         ...  0.         13.86315207
   1.        ]]


In [8]:
print(y_train)

[1 0 1 ... 1 1 1]


In [9]:
print(X_test)

[[ 0.66844295  0.          0.         ...  0.         11.27324516
   1.        ]
 [ 0.68768716  3.18422809  0.         ...  0.          9.90293849
   1.        ]
 [ 0.63707982  0.          0.         ...  0.          7.02170081
   1.        ]
 ...
 [ 0.67953022  0.          0.         ...  0.          6.71471286
   1.        ]
 [ 0.76860284  0.35355339  0.         ...  0.         20.22931545
   1.        ]
 [ 0.66345638  0.          0.         ...  0.          9.91297233
   1.        ]]


In [10]:
print(y_test)

[1 1 1 ... 1 1 1]


## Training the SVM model on the Training set

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2598    0]
 [   0 3402]]


1.0

In [13]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2598
           1       1.00      1.00      1.00      3402

    accuracy                           1.00      6000
   macro avg       1.00      1.00      1.00      6000
weighted avg       1.00      1.00      1.00      6000



In [14]:
from sklearn import svm, metrics
from sklearn.metrics import confusion_matrix
import seaborn as sns
print(confusion_matrix(y_test, y_pred))

print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
print('Sensitivity: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))

[[2598    0]
 [   0 3402]]
Accuracy: 1.000
F1 Score: 1.000
Sensitivity: 1.000
Precision: 1.000
Recall: 1.000
