# Naive Bayes

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('image_bins_lungs2.csv')
X = dataset[['Bins0','Bins1','Bins2','Bins3','Bins4','Bins5','Bins6','Bins7']]
y = dataset.iloc[:, -1].values

In [3]:
print(X)

      Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7
0      4722  15567      4   7683  12061      1   8864  16634
1      6556  13701     25   9956   9437      0  12114  13747
2     10512  12249      1  11502   7743      2   9619  13908
3      7987  11854      2  10419  11895      9  11931  11439
4      7761  14159      4  10898  10560      9   9153  12992
...     ...    ...    ...    ...    ...    ...    ...    ...
2195   7794  14496      0   9859  11028      0   9656  12703
2196   7098   9460      0  11614  15969      0   6950  14445
2197   6380  10094      1  11283  13771      0   7565  16442
2198   6929  13336      1  10413  11515      0   9202  14140
2199   6836   8529      1  11780  16135      0   7419  14836

[2200 rows x 8 columns]


In [4]:
print(y)

[0 0 0 ... 1 1 1]


## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

      Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7
1975   8475  12905      0  11641  10736      0   9634  12145
1287   6246  11456      1  10791  15010      0   7910  14122
760    5554  14950      2  10981  10362      0   6333  17354
267    6153   8235     11  12312  15188      3   7149  16485
2007   7029  13253      1  11101  11710      0   8136  14306
...     ...    ...    ...    ...    ...    ...    ...    ...
1033   7778  11617     67  10570  10957      0   5334  19213
1731   6294  10413      0  11231  14792      0   7561  15245
763    8806  14943      0  12561   7401      0   6238  15587
835   14032  12117      2  13589   4487      2   7471  13836
1653   6257  13971      0  10085  12201      0   8452  14570

[1650 rows x 8 columns]


In [7]:
print(y_train)

[1 1 0 ... 0 0 1]


In [8]:
print(X_test)

      Bins0  Bins1  Bins2  Bins3  Bins4  Bins5  Bins6  Bins7
1320   5966  13036      0  10065  13937      0   7911  14621
1367   5360  13600      0  10336  14742      0   6787  14711
1291   7988  12159      0  10082   8717      0  14705  11885
264   24232  10972   1143    430      0      0      0  28759
728   12349  13640     30  12600   2026      0   6485  18406
...     ...    ...    ...    ...    ...    ...    ...    ...
1999   6645  12845      0  11134  11666      0   8685  14561
1171   7119  13970      9   8907  10878      0  12224  12429
2136   5599  12454      0  11028  14514      0   7100  14841
1882   7046  13604      0  10227  13934      0   7652  13073
938    6689  14310      5   9521  10318      0   7465  17228

[550 rows x 8 columns]


In [9]:
print(y_test)

[1 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1
 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0
 1 0 0 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1
 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1
 1 1 1 1 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0
 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0
 0 1 0 1 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 1 0 1 1
 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1
 1 0 1 1 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 1 0 1 1
 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 1 1 1 0 1 1 0
 0 1 1 1 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 1
 0 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0 1 1 1 1 1
 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 1 1 1
 0 0 1 0 1 1 0 1 0 0 1 1 

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[ 3.30017919e-01  2.50641863e-01 -1.85452806e-01 ... -1.16847411e-01
   4.73659672e-01 -9.02529806e-01]
 [-5.52288578e-01 -3.89729226e-01 -1.61000422e-01 ... -1.16847411e-01
  -1.95934922e-01 -1.65176388e-01]
 [-8.26203381e-01  1.15440920e+00 -1.36548039e-01 ... -1.16847411e-01
  -8.08435312e-01  1.04024913e+00]
 ...
 [ 4.61037861e-01  1.15131562e+00 -1.85452806e-01 ... -1.16847411e-01
  -8.45332926e-01  3.81218532e-01]
 [ 2.52964879e+00 -9.76068727e-02 -1.36548039e-01 ... -5.01549213e-03
  -3.66440737e-01 -2.71844611e-01]
 [-5.47934441e-01  7.21749924e-01 -1.85452806e-01 ... -1.16847411e-01
   1.45756756e-02  1.91229746e-03]]


In [12]:
print(X_test)

[[-0.66312116  0.30853601 -0.18545281 ... -0.11684741 -0.19554653
   0.02093355]
 [-0.90299453  0.55779018 -0.18545281 ... -0.11684741 -0.63210356
   0.05450048]
 [ 0.1372484  -0.07904539 -0.18545281 ... -0.11684741  2.44321546
  -0.99950092]
 ...
 [-0.808391    0.05132691 -0.18545281 ... -0.11684741 -0.51053563
   0.10298603]
 [-0.23562407  0.55955794 -0.18545281 ... -0.11684741 -0.29614107
  -0.55641753]
 [-0.3769356   0.87156759 -0.06319089 ... -0.11684741 -0.36877111
   0.99325544]]


## Training the Naive Bayes model on the Training set

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[151 129]
 [ 17 253]]


0.7345454545454545

In [15]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.54      0.67       280
           1       0.66      0.94      0.78       270

    accuracy                           0.73       550
   macro avg       0.78      0.74      0.73       550
weighted avg       0.78      0.73      0.72       550



In [16]:
from sklearn import svm, metrics
from sklearn.metrics import confusion_matrix
import seaborn as sns
print(confusion_matrix(y_test, y_pred))

print('Accuracy: {0:.3f}'.format(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: {0:.3f}'.format(metrics.f1_score(y_test, y_pred)))
print('Sensitivity: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))
print('Precision: {0:.3f}'.format(metrics.precision_score(y_test, y_pred)))
print('Recall: {0:.3f}'.format(metrics.recall_score(y_test, y_pred)))

[[151 129]
 [ 17 253]]
Accuracy: 0.735
F1 Score: 0.776
Sensitivity: 0.937
Precision: 0.662
Recall: 0.937


In [17]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 71.09 %
Standard Deviation: 1.92 %
